# GENERATED by codegen/generate.ts — DO NOT EDIT
from __future__ import annotations

from typing import Literal

from ._helpers import _ok, _get_client


# ── read ────────────────────────────────────────────────────────────────

def export_all_resources_to_toml(include_resources: bool, tags: list[str] | None = None, include_variables: bool | None = None, include_user_groups: bool | None = None):
    """ExportAllResourcesToToml."""
    params: dict = {"include_resources": include_resources}
    if tags is not None:
        params["tags"] = tags
    if include_variables is not None:
        params["include_variables"] = include_variables
    if include_user_groups is not None:
        params["include_user_groups"] = include_user_groups
    return _ok(_get_client().read("ExportAllResourcesToToml", params))


def export_resources_to_toml(targets: list[dict] | None = None, user_groups: list[str] | None = None, include_variables: bool | None = None):
    """ExportResourcesToToml."""
    params: dict = {}
    if targets is not None:
        params["targets"] = targets
    if user_groups is not None:
        params["user_groups"] = user_groups
    if include_variables is not None:
        params["include_variables"] = include_variables
    return _ok(_get_client().read("ExportResourcesToToml", params or None))


def find_user(user: str):
    """FindUser."""
    return _ok(_get_client().read("FindUser", {"user": user}))


def get_action(action: str):
    """GetAction."""
    return _ok(_get_client().read("GetAction", {"action": action}))


def get_action_action_state(action: str):
    """GetActionActionState."""
    return _ok(_get_client().read("GetActionActionState", {"action": action}))


def get_actions_summary():
    """GetActionsSummary."""
    return _ok(_get_client().read("GetActionsSummary"))


def get_alert(id: str):
    """GetAlert."""
    return _ok(_get_client().read("GetAlert", {"id": id}))


def get_alerter(alerter: str):
    """GetAlerter."""
    return _ok(_get_client().read("GetAlerter", {"alerter": alerter}))


def get_alerters_summary():
    """GetAlertersSummary."""
    return _ok(_get_client().read("GetAlertersSummary"))


def get_build(build: str):
    """GetBuild."""
    return _ok(_get_client().read("GetBuild", {"build": build}))


def get_build_action_state(build: str):
    """GetBuildActionState."""
    return _ok(_get_client().read("GetBuildActionState", {"build": build}))


def get_builder(builder: str):
    """GetBuilder."""
    return _ok(_get_client().read("GetBuilder", {"builder": builder}))


def get_builders_summary():
    """GetBuildersSummary."""
    return _ok(_get_client().read("GetBuildersSummary"))


def get_build_monthly_stats(page: int | None = None):
    """GetBuildMonthlyStats."""
    params: dict = {}
    if page is not None:
        params["page"] = page
    return _ok(_get_client().read("GetBuildMonthlyStats", params or None))


def get_builds_summary():
    """GetBuildsSummary."""
    return _ok(_get_client().read("GetBuildsSummary"))


def get_build_webhook_enabled(build: str):
    """GetBuildWebhookEnabled."""
    return _ok(_get_client().read("GetBuildWebhookEnabled", {"build": build}))


def get_container_log(server: str, container: str, tail: int, timestamps: bool | None = None):
    """GetContainerLog."""
    params: dict = {"server": server, "container": container, "tail": tail}
    if timestamps is not None:
        params["timestamps"] = timestamps
    return _ok(_get_client().read("GetContainerLog", params))


def get_core_info():
    """GetCoreInfo."""
    return _ok(_get_client().read("GetCoreInfo"))


def get_deployment(deployment: str):
    """GetDeployment."""
    return _ok(_get_client().read("GetDeployment", {"deployment": deployment}))


def get_deployment_action_state(deployment: str):
    """GetDeploymentActionState."""
    return _ok(_get_client().read("GetDeploymentActionState", {"deployment": deployment}))


def get_deployment_container(deployment: str):
    """GetDeploymentContainer."""
    return _ok(_get_client().read("GetDeploymentContainer", {"deployment": deployment}))


def get_deployment_log(deployment: str, tail: int, timestamps: bool | None = None):
    """GetDeploymentLog."""
    params: dict = {"deployment": deployment, "tail": tail}
    if timestamps is not None:
        params["timestamps"] = timestamps
    return _ok(_get_client().read("GetDeploymentLog", params))


def get_deployments_summary():
    """GetDeploymentsSummary."""
    return _ok(_get_client().read("GetDeploymentsSummary"))


def get_deployment_stats(deployment: str):
    """GetDeploymentStats."""
    return _ok(_get_client().read("GetDeploymentStats", {"deployment": deployment}))


def get_docker_containers_summary():
    """GetDockerContainersSummary."""
    return _ok(_get_client().read("GetDockerContainersSummary"))


def get_docker_registry_account(id: str):
    """GetDockerRegistryAccount."""
    return _ok(_get_client().read("GetDockerRegistryAccount", {"id": id}))


def get_git_provider_account(id: str):
    """GetGitProviderAccount."""
    return _ok(_get_client().read("GetGitProviderAccount", {"id": id}))


def get_historical_server_stats(server: str, granularity: Literal["1-sec", "5-sec", "10-sec", "15-sec", "30-sec", "1-min", "2-min", "5-min", "10-min", "15-min", "30-min", "1-hr", "2-hr", "6-hr", "8-hr", "12-hr", "1-day", "3-day", "1-wk", "2-wk", "30-day"], page: int | None = None):
    """GetHistoricalServerStats."""
    params: dict = {"server": server, "granularity": granularity}
    if page is not None:
        params["page"] = page
    return _ok(_get_client().read("GetHistoricalServerStats", params))


def get_periphery_version(server: str):
    """GetPeripheryVersion."""
    return _ok(_get_client().read("GetPeripheryVersion", {"server": server}))


def get_permission(target_type: Literal["System", "Server", "Stack", "Deployment", "Build", "Repo", "Procedure", "Action", "Builder", "Alerter", "ResourceSync"], target_id: str):
    """GetPermission."""
    params: dict = {}
    params["target"] = {"type": target_type, "id": target_id}
    return _ok(_get_client().read("GetPermission", params or None))


def get_procedure(procedure: str):
    """GetProcedure."""
    return _ok(_get_client().read("GetProcedure", {"procedure": procedure}))


def get_procedure_action_state(procedure: str):
    """GetProcedureActionState."""
    return _ok(_get_client().read("GetProcedureActionState", {"procedure": procedure}))


def get_procedures_summary():
    """GetProceduresSummary."""
    return _ok(_get_client().read("GetProceduresSummary"))


def get_repo(repo: str):
    """GetRepo."""
    return _ok(_get_client().read("GetRepo", {"repo": repo}))


def get_repo_action_state(repo: str):
    """GetRepoActionState."""
    return _ok(_get_client().read("GetRepoActionState", {"repo": repo}))


def get_repos_summary():
    """GetReposSummary."""
    return _ok(_get_client().read("GetReposSummary"))


def get_repo_webhooks_enabled(repo: str):
    """GetRepoWebhooksEnabled."""
    return _ok(_get_client().read("GetRepoWebhooksEnabled", {"repo": repo}))


def get_resource_matching_container(server: str, container: str):
    """GetResourceMatchingContainer."""
    return _ok(_get_client().read("GetResourceMatchingContainer", {"server": server, "container": container}))


def get_resource_sync(sync: str):
    """GetResourceSync."""
    return _ok(_get_client().read("GetResourceSync", {"sync": sync}))


def get_resource_sync_action_state(sync: str):
    """GetResourceSyncActionState."""
    return _ok(_get_client().read("GetResourceSyncActionState", {"sync": sync}))


def get_resource_syncs_summary():
    """GetResourceSyncsSummary."""
    return _ok(_get_client().read("GetResourceSyncsSummary"))


def get_server(server: str):
    """GetServer."""
    return _ok(_get_client().read("GetServer", {"server": server}))


def get_server_action_state(server: str):
    """GetServerActionState."""
    return _ok(_get_client().read("GetServerActionState", {"server": server}))


def get_servers_summary():
    """GetServersSummary."""
    return _ok(_get_client().read("GetServersSummary"))


def get_server_state(server: str):
    """GetServerState."""
    return _ok(_get_client().read("GetServerState", {"server": server}))


def get_stack(stack: str):
    """GetStack."""
    return _ok(_get_client().read("GetStack", {"stack": stack}))


def get_stack_action_state(stack: str):
    """GetStackActionState."""
    return _ok(_get_client().read("GetStackActionState", {"stack": stack}))


def get_stack_log(stack: str, services: list[str], tail: int, timestamps: bool | None = None):
    """GetStackLog."""
    params: dict = {"stack": stack, "services": services, "tail": tail}
    if timestamps is not None:
        params["timestamps"] = timestamps
    return _ok(_get_client().read("GetStackLog", params))


def get_stacks_summary():
    """GetStacksSummary."""
    return _ok(_get_client().read("GetStacksSummary"))


def get_stack_webhooks_enabled(stack: str):
    """GetStackWebhooksEnabled."""
    return _ok(_get_client().read("GetStackWebhooksEnabled", {"stack": stack}))


def get_sync_webhooks_enabled(sync: str):
    """GetSyncWebhooksEnabled."""
    return _ok(_get_client().read("GetSyncWebhooksEnabled", {"sync": sync}))


def get_system_information(server: str):
    """GetSystemInformation."""
    return _ok(_get_client().read("GetSystemInformation", {"server": server}))


def get_system_stats(server: str):
    """GetSystemStats."""
    return _ok(_get_client().read("GetSystemStats", {"server": server}))


def get_tag(tag: str):
    """GetTag."""
    return _ok(_get_client().read("GetTag", {"tag": tag}))


def get_update(id: str):
    """GetUpdate."""
    return _ok(_get_client().read("GetUpdate", {"id": id}))


def get_user_group(user_group: str):
    """GetUserGroup."""
    return _ok(_get_client().read("GetUserGroup", {"user_group": user_group}))


def get_username(user_id: str):
    """GetUsername."""
    return _ok(_get_client().read("GetUsername", {"user_id": user_id}))


def get_variable(name: str):
    """GetVariable."""
    return _ok(_get_client().read("GetVariable", {"name": name}))


def get_version():
    """GetVersion."""
    return _ok(_get_client().read("GetVersion"))


def inspect_deployment_container(deployment: str):
    """InspectDeploymentContainer."""
    return _ok(_get_client().read("InspectDeploymentContainer", {"deployment": deployment}))


def inspect_docker_container(server: str, container: str):
    """InspectDockerContainer."""
    return _ok(_get_client().read("InspectDockerContainer", {"server": server, "container": container}))


def inspect_docker_image(server: str, image: str):
    """InspectDockerImage."""
    return _ok(_get_client().read("InspectDockerImage", {"server": server, "image": image}))


def inspect_docker_network(server: str, network: str):
    """InspectDockerNetwork."""
    return _ok(_get_client().read("InspectDockerNetwork", {"server": server, "network": network}))


def inspect_docker_volume(server: str, volume: str):
    """InspectDockerVolume."""
    return _ok(_get_client().read("InspectDockerVolume", {"server": server, "volume": volume}))


def inspect_stack_container(stack: str, service: str):
    """InspectStackContainer."""
    return _ok(_get_client().read("InspectStackContainer", {"stack": stack, "service": service}))


def list_actions(names: list[str] | None = None, templates: Literal["Include", "Exclude", "Only"] | None = None, tags: list[str] | None = None, tag_behavior: Literal["All", "Any"] | None = None):
    """ListActions."""
    params: dict = {}
    _query: dict = {}
    if names is not None:
        _query["names"] = names
    if templates is not None:
        _query["templates"] = templates
    if tags is not None:
        _query["tags"] = tags
    if tag_behavior is not None:
        _query["tag_behavior"] = tag_behavior
    if _query:
        params["query"] = _query
    return _ok(_get_client().read("ListActions", params or None))


def list_alerters(names: list[str] | None = None, templates: Literal["Include", "Exclude", "Only"] | None = None, tags: list[str] | None = None, tag_behavior: Literal["All", "Any"] | None = None, enabled: bool | None = None, types: list[Literal["Custom", "Slack", "Discord", "Ntfy", "Pushover"]] | None = None):
    """ListAlerters."""
    params: dict = {}
    _query: dict = {}
    if names is not None:
        _query["names"] = names
    if templates is not None:
        _query["templates"] = templates
    if tags is not None:
        _query["tags"] = tags
    if tag_behavior is not None:
        _query["tag_behavior"] = tag_behavior
    _specific: dict = {}
    if enabled is not None:
        _specific["enabled"] = enabled
    if types is not None:
        _specific["types"] = types
    if _specific:
        _query["specific"] = _specific
    if _query:
        params["query"] = _query
    return _ok(_get_client().read("ListAlerters", params or None))


def list_alerts(query: dict | None = None, page: int | None = None):
    """ListAlerts."""
    params: dict = {}
    if query is not None:
        params["query"] = query
    if page is not None:
        params["page"] = page
    return _ok(_get_client().read("ListAlerts", params or None))


def list_all_docker_containers(servers: list[str] | None = None):
    """ListAllDockerContainers."""
    params: dict = {}
    if servers is not None:
        params["servers"] = servers
    return _ok(_get_client().read("ListAllDockerContainers", params or None))


def list_api_keys():
    """ListApiKeys."""
    return _ok(_get_client().read("ListApiKeys"))


def list_api_keys_for_service_user(user: str):
    """ListApiKeysForServiceUser."""
    return _ok(_get_client().read("ListApiKeysForServiceUser", {"user": user}))


def list_builders(names: list[str] | None = None, templates: Literal["Include", "Exclude", "Only"] | None = None, tags: list[str] | None = None, tag_behavior: Literal["All", "Any"] | None = None):
    """ListBuilders."""
    params: dict = {}
    _query: dict = {}
    if names is not None:
        _query["names"] = names
    if templates is not None:
        _query["templates"] = templates
    if tags is not None:
        _query["tags"] = tags
    if tag_behavior is not None:
        _query["tag_behavior"] = tag_behavior
    if _query:
        params["query"] = _query
    return _ok(_get_client().read("ListBuilders", params or None))


def list_builds(names: list[str] | None = None, templates: Literal["Include", "Exclude", "Only"] | None = None, tags: list[str] | None = None, tag_behavior: Literal["All", "Any"] | None = None, builder_ids: list[str] | None = None, repos: list[str] | None = None, built_since: int | None = None):
    """ListBuilds."""
    params: dict = {}
    _query: dict = {}
    if names is not None:
        _query["names"] = names
    if templates is not None:
        _query["templates"] = templates
    if tags is not None:
        _query["tags"] = tags
    if tag_behavior is not None:
        _query["tag_behavior"] = tag_behavior
    _specific: dict = {}
    if builder_ids is not None:
        _specific["builder_ids"] = builder_ids
    if repos is not None:
        _specific["repos"] = repos
    if built_since is not None:
        _specific["built_since"] = built_since
    if _specific:
        _query["specific"] = _specific
    if _query:
        params["query"] = _query
    return _ok(_get_client().read("ListBuilds", params or None))


def list_build_versions(build: str, major: int | None = None, minor: int | None = None, patch: int | None = None, limit: int | None = None):
    """ListBuildVersions."""
    params: dict = {"build": build}
    if major is not None:
        params["major"] = major
    if minor is not None:
        params["minor"] = minor
    if patch is not None:
        params["patch"] = patch
    if limit is not None:
        params["limit"] = limit
    return _ok(_get_client().read("ListBuildVersions", params))


def list_common_build_extra_args(names: list[str] | None = None, templates: Literal["Include", "Exclude", "Only"] | None = None, tags: list[str] | None = None, tag_behavior: Literal["All", "Any"] | None = None, builder_ids: list[str] | None = None, repos: list[str] | None = None, built_since: int | None = None):
    """ListCommonBuildExtraArgs."""
    params: dict = {}
    _query: dict = {}
    if names is not None:
        _query["names"] = names
    if templates is not None:
        _query["templates"] = templates
    if tags is not None:
        _query["tags"] = tags
    if tag_behavior is not None:
        _query["tag_behavior"] = tag_behavior
    _specific: dict = {}
    if builder_ids is not None:
        _specific["builder_ids"] = builder_ids
    if repos is not None:
        _specific["repos"] = repos
    if built_since is not None:
        _specific["built_since"] = built_since
    if _specific:
        _query["specific"] = _specific
    if _query:
        params["query"] = _query
    return _ok(_get_client().read("ListCommonBuildExtraArgs", params or None))


def list_common_deployment_extra_args(names: list[str] | None = None, templates: Literal["Include", "Exclude", "Only"] | None = None, tags: list[str] | None = None, tag_behavior: Literal["All", "Any"] | None = None, server_ids: list[str] | None = None, build_ids: list[str] | None = None, update_available: bool | None = None):
    """ListCommonDeploymentExtraArgs."""
    params: dict = {}
    _query: dict = {}
    if names is not None:
        _query["names"] = names
    if templates is not None:
        _query["templates"] = templates
    if tags is not None:
        _query["tags"] = tags
    if tag_behavior is not None:
        _query["tag_behavior"] = tag_behavior
    _specific: dict = {}
    if server_ids is not None:
        _specific["server_ids"] = server_ids
    if build_ids is not None:
        _specific["build_ids"] = build_ids
    if update_available is not None:
        _specific["update_available"] = update_available
    if _specific:
        _query["specific"] = _specific
    if _query:
        params["query"] = _query
    return _ok(_get_client().read("ListCommonDeploymentExtraArgs", params or None))


def list_common_stack_build_extra_args(names: list[str] | None = None, templates: Literal["Include", "Exclude", "Only"] | None = None, tags: list[str] | None = None, tag_behavior: Literal["All", "Any"] | None = None, server_ids: list[str] | None = None, linked_repos: list[str] | None = None, repos: list[str] | None = None, update_available: bool | None = None):
    """ListCommonStackBuildExtraArgs."""
    params: dict = {}
    _query: dict = {}
    if names is not None:
        _query["names"] = names
    if templates is not None:
        _query["templates"] = templates
    if tags is not None:
        _query["tags"] = tags
    if tag_behavior is not None:
        _query["tag_behavior"] = tag_behavior
    _specific: dict = {}
    if server_ids is not None:
        _specific["server_ids"] = server_ids
    if linked_repos is not None:
        _specific["linked_repos"] = linked_repos
    if repos is not None:
        _specific["repos"] = repos
    if update_available is not None:
        _specific["update_available"] = update_available
    if _specific:
        _query["specific"] = _specific
    if _query:
        params["query"] = _query
    return _ok(_get_client().read("ListCommonStackBuildExtraArgs", params or None))


def list_common_stack_extra_args(names: list[str] | None = None, templates: Literal["Include", "Exclude", "Only"] | None = None, tags: list[str] | None = None, tag_behavior: Literal["All", "Any"] | None = None, server_ids: list[str] | None = None, linked_repos: list[str] | None = None, repos: list[str] | None = None, update_available: bool | None = None):
    """ListCommonStackExtraArgs."""
    params: dict = {}
    _query: dict = {}
    if names is not None:
        _query["names"] = names
    if templates is not None:
        _query["templates"] = templates
    if tags is not None:
        _query["tags"] = tags
    if tag_behavior is not None:
        _query["tag_behavior"] = tag_behavior
    _specific: dict = {}
    if server_ids is not None:
        _specific["server_ids"] = server_ids
    if linked_repos is not None:
        _specific["linked_repos"] = linked_repos
    if repos is not None:
        _specific["repos"] = repos
    if update_available is not None:
        _specific["update_available"] = update_available
    if _specific:
        _query["specific"] = _specific
    if _query:
        params["query"] = _query
    return _ok(_get_client().read("ListCommonStackExtraArgs", params or None))


def list_compose_projects(server: str):
    """ListComposeProjects."""
    return _ok(_get_client().read("ListComposeProjects", {"server": server}))


def list_deployments(names: list[str] | None = None, templates: Literal["Include", "Exclude", "Only"] | None = None, tags: list[str] | None = None, tag_behavior: Literal["All", "Any"] | None = None, server_ids: list[str] | None = None, build_ids: list[str] | None = None, update_available: bool | None = None):
    """ListDeployments."""
    params: dict = {}
    _query: dict = {}
    if names is not None:
        _query["names"] = names
    if templates is not None:
        _query["templates"] = templates
    if tags is not None:
        _query["tags"] = tags
    if tag_behavior is not None:
        _query["tag_behavior"] = tag_behavior
    _specific: dict = {}
    if server_ids is not None:
        _specific["server_ids"] = server_ids
    if build_ids is not None:
        _specific["build_ids"] = build_ids
    if update_available is not None:
        _specific["update_available"] = update_available
    if _specific:
        _query["specific"] = _specific
    if _query:
        params["query"] = _query
    return _ok(_get_client().read("ListDeployments", params or None))


def list_docker_containers(server: str):
    """ListDockerContainers."""
    return _ok(_get_client().read("ListDockerContainers", {"server": server}))


def list_docker_image_history(server: str, image: str):
    """ListDockerImageHistory."""
    return _ok(_get_client().read("ListDockerImageHistory", {"server": server, "image": image}))


def list_docker_images(server: str):
    """ListDockerImages."""
    return _ok(_get_client().read("ListDockerImages", {"server": server}))


def list_docker_networks(server: str):
    """ListDockerNetworks."""
    return _ok(_get_client().read("ListDockerNetworks", {"server": server}))


def list_docker_registries_from_config(target_type: Literal["System", "Server", "Stack", "Deployment", "Build", "Repo", "Procedure", "Action", "Builder", "Alerter", "ResourceSync"] | None = None, target_id: str | None = None):
    """ListDockerRegistriesFromConfig."""
    params: dict = {}
    if target_type is not None and target_id is not None:
        params["target"] = {"type": target_type, "id": target_id}
    return _ok(_get_client().read("ListDockerRegistriesFromConfig", params or None))


def list_docker_registry_accounts(domain: str | None = None, username: str | None = None):
    """ListDockerRegistryAccounts."""
    params: dict = {}
    if domain is not None:
        params["domain"] = domain
    if username is not None:
        params["username"] = username
    return _ok(_get_client().read("ListDockerRegistryAccounts", params or None))


def list_docker_volumes(server: str):
    """ListDockerVolumes."""
    return _ok(_get_client().read("ListDockerVolumes", {"server": server}))


def list_full_actions(names: list[str] | None = None, templates: Literal["Include", "Exclude", "Only"] | None = None, tags: list[str] | None = None, tag_behavior: Literal["All", "Any"] | None = None):
    """ListFullActions."""
    params: dict = {}
    _query: dict = {}
    if names is not None:
        _query["names"] = names
    if templates is not None:
        _query["templates"] = templates
    if tags is not None:
        _query["tags"] = tags
    if tag_behavior is not None:
        _query["tag_behavior"] = tag_behavior
    if _query:
        params["query"] = _query
    return _ok(_get_client().read("ListFullActions", params or None))


def list_full_alerters(names: list[str] | None = None, templates: Literal["Include", "Exclude", "Only"] | None = None, tags: list[str] | None = None, tag_behavior: Literal["All", "Any"] | None = None, enabled: bool | None = None, types: list[Literal["Custom", "Slack", "Discord", "Ntfy", "Pushover"]] | None = None):
    """ListFullAlerters."""
    params: dict = {}
    _query: dict = {}
    if names is not None:
        _query["names"] = names
    if templates is not None:
        _query["templates"] = templates
    if tags is not None:
        _query["tags"] = tags
    if tag_behavior is not None:
        _query["tag_behavior"] = tag_behavior
    _specific: dict = {}
    if enabled is not None:
        _specific["enabled"] = enabled
    if types is not None:
        _specific["types"] = types
    if _specific:
        _query["specific"] = _specific
    if _query:
        params["query"] = _query
    return _ok(_get_client().read("ListFullAlerters", params or None))


def list_full_builders(names: list[str] | None = None, templates: Literal["Include", "Exclude", "Only"] | None = None, tags: list[str] | None = None, tag_behavior: Literal["All", "Any"] | None = None):
    """ListFullBuilders."""
    params: dict = {}
    _query: dict = {}
    if names is not None:
        _query["names"] = names
    if templates is not None:
        _query["templates"] = templates
    if tags is not None:
        _query["tags"] = tags
    if tag_behavior is not None:
        _query["tag_behavior"] = tag_behavior
    if _query:
        params["query"] = _query
    return _ok(_get_client().read("ListFullBuilders", params or None))


def list_full_builds(names: list[str] | None = None, templates: Literal["Include", "Exclude", "Only"] | None = None, tags: list[str] | None = None, tag_behavior: Literal["All", "Any"] | None = None, builder_ids: list[str] | None = None, repos: list[str] | None = None, built_since: int | None = None):
    """ListFullBuilds."""
    params: dict = {}
    _query: dict = {}
    if names is not None:
        _query["names"] = names
    if templates is not None:
        _query["templates"] = templates
    if tags is not None:
        _query["tags"] = tags
    if tag_behavior is not None:
        _query["tag_behavior"] = tag_behavior
    _specific: dict = {}
    if builder_ids is not None:
        _specific["builder_ids"] = builder_ids
    if repos is not None:
        _specific["repos"] = repos
    if built_since is not None:
        _specific["built_since"] = built_since
    if _specific:
        _query["specific"] = _specific
    if _query:
        params["query"] = _query
    return _ok(_get_client().read("ListFullBuilds", params or None))


def list_full_deployments(names: list[str] | None = None, templates: Literal["Include", "Exclude", "Only"] | None = None, tags: list[str] | None = None, tag_behavior: Literal["All", "Any"] | None = None, server_ids: list[str] | None = None, build_ids: list[str] | None = None, update_available: bool | None = None):
    """ListFullDeployments."""
    params: dict = {}
    _query: dict = {}
    if names is not None:
        _query["names"] = names
    if templates is not None:
        _query["templates"] = templates
    if tags is not None:
        _query["tags"] = tags
    if tag_behavior is not None:
        _query["tag_behavior"] = tag_behavior
    _specific: dict = {}
    if server_ids is not None:
        _specific["server_ids"] = server_ids
    if build_ids is not None:
        _specific["build_ids"] = build_ids
    if update_available is not None:
        _specific["update_available"] = update_available
    if _specific:
        _query["specific"] = _specific
    if _query:
        params["query"] = _query
    return _ok(_get_client().read("ListFullDeployments", params or None))


def list_full_procedures(names: list[str] | None = None, templates: Literal["Include", "Exclude", "Only"] | None = None, tags: list[str] | None = None, tag_behavior: Literal["All", "Any"] | None = None):
    """ListFullProcedures."""
    params: dict = {}
    _query: dict = {}
    if names is not None:
        _query["names"] = names
    if templates is not None:
        _query["templates"] = templates
    if tags is not None:
        _query["tags"] = tags
    if tag_behavior is not None:
        _query["tag_behavior"] = tag_behavior
    if _query:
        params["query"] = _query
    return _ok(_get_client().read("ListFullProcedures", params or None))


def list_full_repos(names: list[str] | None = None, templates: Literal["Include", "Exclude", "Only"] | None = None, tags: list[str] | None = None, tag_behavior: Literal["All", "Any"] | None = None, repos: list[str] | None = None):
    """ListFullRepos."""
    params: dict = {}
    _query: dict = {}
    if names is not None:
        _query["names"] = names
    if templates is not None:
        _query["templates"] = templates
    if tags is not None:
        _query["tags"] = tags
    if tag_behavior is not None:
        _query["tag_behavior"] = tag_behavior
    _specific: dict = {}
    if repos is not None:
        _specific["repos"] = repos
    if _specific:
        _query["specific"] = _specific
    if _query:
        params["query"] = _query
    return _ok(_get_client().read("ListFullRepos", params or None))


def list_full_resource_syncs(names: list[str] | None = None, templates: Literal["Include", "Exclude", "Only"] | None = None, tags: list[str] | None = None, tag_behavior: Literal["All", "Any"] | None = None, repos: list[str] | None = None):
    """ListFullResourceSyncs."""
    params: dict = {}
    _query: dict = {}
    if names is not None:
        _query["names"] = names
    if templates is not None:
        _query["templates"] = templates
    if tags is not None:
        _query["tags"] = tags
    if tag_behavior is not None:
        _query["tag_behavior"] = tag_behavior
    _specific: dict = {}
    if repos is not None:
        _specific["repos"] = repos
    if _specific:
        _query["specific"] = _specific
    if _query:
        params["query"] = _query
    return _ok(_get_client().read("ListFullResourceSyncs", params or None))


def list_full_servers(names: list[str] | None = None, templates: Literal["Include", "Exclude", "Only"] | None = None, tags: list[str] | None = None, tag_behavior: Literal["All", "Any"] | None = None):
    """ListFullServers."""
    params: dict = {}
    _query: dict = {}
    if names is not None:
        _query["names"] = names
    if templates is not None:
        _query["templates"] = templates
    if tags is not None:
        _query["tags"] = tags
    if tag_behavior is not None:
        _query["tag_behavior"] = tag_behavior
    if _query:
        params["query"] = _query
    return _ok(_get_client().read("ListFullServers", params or None))


def list_full_stacks(names: list[str] | None = None, templates: Literal["Include", "Exclude", "Only"] | None = None, tags: list[str] | None = None, tag_behavior: Literal["All", "Any"] | None = None, server_ids: list[str] | None = None, linked_repos: list[str] | None = None, repos: list[str] | None = None, update_available: bool | None = None):
    """ListFullStacks."""
    params: dict = {}
    _query: dict = {}
    if names is not None:
        _query["names"] = names
    if templates is not None:
        _query["templates"] = templates
    if tags is not None:
        _query["tags"] = tags
    if tag_behavior is not None:
        _query["tag_behavior"] = tag_behavior
    _specific: dict = {}
    if server_ids is not None:
        _specific["server_ids"] = server_ids
    if linked_repos is not None:
        _specific["linked_repos"] = linked_repos
    if repos is not None:
        _specific["repos"] = repos
    if update_available is not None:
        _specific["update_available"] = update_available
    if _specific:
        _query["specific"] = _specific
    if _query:
        params["query"] = _query
    return _ok(_get_client().read("ListFullStacks", params or None))


def list_git_provider_accounts(domain: str | None = None, username: str | None = None):
    """ListGitProviderAccounts."""
    params: dict = {}
    if domain is not None:
        params["domain"] = domain
    if username is not None:
        params["username"] = username
    return _ok(_get_client().read("ListGitProviderAccounts", params or None))


def list_git_providers_from_config(target_type: Literal["System", "Server", "Stack", "Deployment", "Build", "Repo", "Procedure", "Action", "Builder", "Alerter", "ResourceSync"] | None = None, target_id: str | None = None):
    """ListGitProvidersFromConfig."""
    params: dict = {}
    if target_type is not None and target_id is not None:
        params["target"] = {"type": target_type, "id": target_id}
    return _ok(_get_client().read("ListGitProvidersFromConfig", params or None))


def list_permissions():
    """ListPermissions."""
    return _ok(_get_client().read("ListPermissions"))


def list_procedures(names: list[str] | None = None, templates: Literal["Include", "Exclude", "Only"] | None = None, tags: list[str] | None = None, tag_behavior: Literal["All", "Any"] | None = None):
    """ListProcedures."""
    params: dict = {}
    _query: dict = {}
    if names is not None:
        _query["names"] = names
    if templates is not None:
        _query["templates"] = templates
    if tags is not None:
        _query["tags"] = tags
    if tag_behavior is not None:
        _query["tag_behavior"] = tag_behavior
    if _query:
        params["query"] = _query
    return _ok(_get_client().read("ListProcedures", params or None))


def list_repos(names: list[str] | None = None, templates: Literal["Include", "Exclude", "Only"] | None = None, tags: list[str] | None = None, tag_behavior: Literal["All", "Any"] | None = None, repos: list[str] | None = None):
    """ListRepos."""
    params: dict = {}
    _query: dict = {}
    if names is not None:
        _query["names"] = names
    if templates is not None:
        _query["templates"] = templates
    if tags is not None:
        _query["tags"] = tags
    if tag_behavior is not None:
        _query["tag_behavior"] = tag_behavior
    _specific: dict = {}
    if repos is not None:
        _specific["repos"] = repos
    if _specific:
        _query["specific"] = _specific
    if _query:
        params["query"] = _query
    return _ok(_get_client().read("ListRepos", params or None))


def list_resource_syncs(names: list[str] | None = None, templates: Literal["Include", "Exclude", "Only"] | None = None, tags: list[str] | None = None, tag_behavior: Literal["All", "Any"] | None = None, repos: list[str] | None = None):
    """ListResourceSyncs."""
    params: dict = {}
    _query: dict = {}
    if names is not None:
        _query["names"] = names
    if templates is not None:
        _query["templates"] = templates
    if tags is not None:
        _query["tags"] = tags
    if tag_behavior is not None:
        _query["tag_behavior"] = tag_behavior
    _specific: dict = {}
    if repos is not None:
        _specific["repos"] = repos
    if _specific:
        _query["specific"] = _specific
    if _query:
        params["query"] = _query
    return _ok(_get_client().read("ListResourceSyncs", params or None))


def list_schedules(tags: list[str] | None = None, tag_behavior: Literal["All", "Any"] | None = None):
    """ListSchedules."""
    params: dict = {}
    if tags is not None:
        params["tags"] = tags
    if tag_behavior is not None:
        params["tag_behavior"] = tag_behavior
    return _ok(_get_client().read("ListSchedules", params or None))


def list_secrets(target_type: Literal["System", "Server", "Stack", "Deployment", "Build", "Repo", "Procedure", "Action", "Builder", "Alerter", "ResourceSync"] | None = None, target_id: str | None = None):
    """ListSecrets."""
    params: dict = {}
    if target_type is not None and target_id is not None:
        params["target"] = {"type": target_type, "id": target_id}
    return _ok(_get_client().read("ListSecrets", params or None))


def list_servers(names: list[str] | None = None, templates: Literal["Include", "Exclude", "Only"] | None = None, tags: list[str] | None = None, tag_behavior: Literal["All", "Any"] | None = None):
    """ListServers."""
    params: dict = {}
    _query: dict = {}
    if names is not None:
        _query["names"] = names
    if templates is not None:
        _query["templates"] = templates
    if tags is not None:
        _query["tags"] = tags
    if tag_behavior is not None:
        _query["tag_behavior"] = tag_behavior
    if _query:
        params["query"] = _query
    return _ok(_get_client().read("ListServers", params or None))


def list_stacks(names: list[str] | None = None, templates: Literal["Include", "Exclude", "Only"] | None = None, tags: list[str] | None = None, tag_behavior: Literal["All", "Any"] | None = None, server_ids: list[str] | None = None, linked_repos: list[str] | None = None, repos: list[str] | None = None, update_available: bool | None = None):
    """ListStacks."""
    params: dict = {}
    _query: dict = {}
    if names is not None:
        _query["names"] = names
    if templates is not None:
        _query["templates"] = templates
    if tags is not None:
        _query["tags"] = tags
    if tag_behavior is not None:
        _query["tag_behavior"] = tag_behavior
    _specific: dict = {}
    if server_ids is not None:
        _specific["server_ids"] = server_ids
    if linked_repos is not None:
        _specific["linked_repos"] = linked_repos
    if repos is not None:
        _specific["repos"] = repos
    if update_available is not None:
        _specific["update_available"] = update_available
    if _specific:
        _query["specific"] = _specific
    if _query:
        params["query"] = _query
    return _ok(_get_client().read("ListStacks", params or None))


def list_stack_services(stack: str):
    """ListStackServices."""
    return _ok(_get_client().read("ListStackServices", {"stack": stack}))


def list_system_processes(server: str):
    """ListSystemProcesses."""
    return _ok(_get_client().read("ListSystemProcesses", {"server": server}))


def list_tags(query: dict | None = None):
    """ListTags."""
    params: dict = {}
    if query is not None:
        params["query"] = query
    return _ok(_get_client().read("ListTags", params or None))


def list_terminals(server: str, fresh: bool | None = None):
    """ListTerminals."""
    params: dict = {"server": server}
    if fresh is not None:
        params["fresh"] = fresh
    return _ok(_get_client().read("ListTerminals", params))


def list_updates(query: dict | None = None, page: int | None = None):
    """ListUpdates."""
    params: dict = {}
    if query is not None:
        params["query"] = query
    if page is not None:
        params["page"] = page
    return _ok(_get_client().read("ListUpdates", params or None))


def list_user_groups():
    """ListUserGroups."""
    return _ok(_get_client().read("ListUserGroups"))


def list_users():
    """ListUsers."""
    return _ok(_get_client().read("ListUsers"))


def list_user_target_permissions(user_target_type: Literal["User", "UserGroup"], user_target_id: str):
    """ListUserTargetPermissions."""
    params: dict = {}
    params["user_target"] = {"type": user_target_type, "id": user_target_id}
    return _ok(_get_client().read("ListUserTargetPermissions", params or None))


def list_variables():
    """ListVariables."""
    return _ok(_get_client().read("ListVariables"))


def search_container_log(server: str, container: str, terms: list[str], combinator: Literal["Or", "And"] | None = None, invert: bool | None = None, timestamps: bool | None = None):
    """SearchContainerLog."""
    params: dict = {"server": server, "container": container, "terms": terms}
    if combinator is not None:
        params["combinator"] = combinator
    if invert is not None:
        params["invert"] = invert
    if timestamps is not None:
        params["timestamps"] = timestamps
    return _ok(_get_client().read("SearchContainerLog", params))


def search_deployment_log(deployment: str, terms: list[str], combinator: Literal["Or", "And"] | None = None, invert: bool | None = None, timestamps: bool | None = None):
    """SearchDeploymentLog."""
    params: dict = {"deployment": deployment, "terms": terms}
    if combinator is not None:
        params["combinator"] = combinator
    if invert is not None:
        params["invert"] = invert
    if timestamps is not None:
        params["timestamps"] = timestamps
    return _ok(_get_client().read("SearchDeploymentLog", params))


def search_stack_log(stack: str, services: list[str], terms: list[str], combinator: Literal["Or", "And"] | None = None, invert: bool | None = None, timestamps: bool | None = None):
    """SearchStackLog."""
    params: dict = {"stack": stack, "services": services, "terms": terms}
    if combinator is not None:
        params["combinator"] = combinator
    if invert is not None:
        params["invert"] = invert
    if timestamps is not None:
        params["timestamps"] = timestamps
    return _ok(_get_client().read("SearchStackLog", params))


# ── write ───────────────────────────────────────────────────────────────

def add_user_to_user_group(user_group: str, user: str):
    """AddUserToUserGroup."""
    return _ok(_get_client().write("AddUserToUserGroup", {"user_group": user_group, "user": user}))


def commit_sync(sync: str):
    """CommitSync."""
    return _ok(_get_client().write("CommitSync", {"sync": sync}))


def copy_action(name: str, id: str):
    """CopyAction."""
    return _ok(_get_client().write("CopyAction", {"name": name, "id": id}))


def copy_alerter(name: str, id: str):
    """CopyAlerter."""
    return _ok(_get_client().write("CopyAlerter", {"name": name, "id": id}))


def copy_build(name: str, id: str):
    """CopyBuild."""
    return _ok(_get_client().write("CopyBuild", {"name": name, "id": id}))


def copy_builder(name: str, id: str):
    """CopyBuilder."""
    return _ok(_get_client().write("CopyBuilder", {"name": name, "id": id}))


def copy_deployment(name: str, id: str):
    """CopyDeployment."""
    return _ok(_get_client().write("CopyDeployment", {"name": name, "id": id}))


def copy_procedure(name: str, id: str):
    """CopyProcedure."""
    return _ok(_get_client().write("CopyProcedure", {"name": name, "id": id}))


def copy_repo(name: str, id: str):
    """CopyRepo."""
    return _ok(_get_client().write("CopyRepo", {"name": name, "id": id}))


def copy_resource_sync(name: str, id: str):
    """CopyResourceSync."""
    return _ok(_get_client().write("CopyResourceSync", {"name": name, "id": id}))


def copy_server(name: str, id: str):
    """CopyServer."""
    return _ok(_get_client().write("CopyServer", {"name": name, "id": id}))


def copy_stack(name: str, id: str):
    """CopyStack."""
    return _ok(_get_client().write("CopyStack", {"name": name, "id": id}))


def create_action(name: str, config: dict | None = None):
    """CreateAction.

    config fields: run_at_startup (bool), schedule_format (Literal["English", "Cron"]), schedule (str), schedule_enabled (bool), schedule_timezone (str), schedule_alert (bool), failure_alert (bool), webhook_enabled (bool), webhook_secret (str), reload_deno_deps (bool), file_contents (str), arguments_format (Literal["key_value", "toml", "yaml", "json"]), arguments (str)
    """
    params: dict = {"name": name}
    if config is not None:
        params["config"] = config
    return _ok(_get_client().write("CreateAction", params))


def create_alerter(name: str, config: dict | None = None):
    """CreateAlerter.

    config fields: enabled (bool), endpoint (dict), alert_types (list[Literal["Custom", "None", "Test", "ServerUnreachable", "ServerCpu", "ServerMem", "ServerDisk", "ServerVersionMismatch", "ContainerStateChange", "DeploymentImageUpdateAvailable", "DeploymentAutoUpdated", "StackStateChange", "StackImageUpdateAvailable", "StackAutoUpdated", "AwsBuilderTerminationFailed", "ResourceSyncPendingUpdates", "BuildFailed", "RepoBuildFailed", "ProcedureFailed", "ActionFailed", "ScheduleRun"]]), resources (list[dict]), except_resources (list[dict]), maintenance_windows (list[dict])
    """
    params: dict = {"name": name}
    if config is not None:
        params["config"] = config
    return _ok(_get_client().write("CreateAlerter", params))


def create_api_key_for_service_user(user_id: str, name: str, expires: int | None = None):
    """CreateApiKeyForServiceUser."""
    params: dict = {"user_id": user_id, "name": name}
    if expires is not None:
        params["expires"] = expires
    return _ok(_get_client().write("CreateApiKeyForServiceUser", params))


def create_build(name: str, config: dict | None = None):
    """CreateBuild.

    config fields: builder_id (str), version (dict), auto_increment_version (bool), image_name (str), image_tag (str), include_latest_tag (bool), include_version_tags (bool), include_commit_tag (bool), links (list[str]), linked_repo (str), git_provider (str), git_https (bool), git_account (str), repo (str), branch (str), ...
    """
    params: dict = {"name": name}
    if config is not None:
        params["config"] = config
    return _ok(_get_client().write("CreateBuild", params))


def create_builder(name: str, config: dict | None = None):
    """CreateBuilder."""
    params: dict = {"name": name}
    if config is not None:
        params["config"] = config
    return _ok(_get_client().write("CreateBuilder", params))


def create_build_webhook(build: str):
    """CreateBuildWebhook."""
    return _ok(_get_client().write("CreateBuildWebhook", {"build": build}))


def create_deployment(name: str, config: dict | None = None):
    """CreateDeployment.

    config fields: server_id (str), image (dict), image_registry_account (str), skip_secret_interp (bool), redeploy_on_build (bool), poll_for_updates (bool), auto_update (bool), send_alerts (bool), links (list[str]), network (str), restart (Literal["no", "on-failure", "always", "unless-stopped"]), command (str), termination_signal (Literal["SIGHUP", "SIGINT", "SIGQUIT", "SIGTERM"]), termination_timeout (int), extra_args (list[str]), ...
    """
    params: dict = {"name": name}
    if config is not None:
        params["config"] = config
    return _ok(_get_client().write("CreateDeployment", params))


def create_deployment_from_container(name: str, server: str):
    """CreateDeploymentFromContainer."""
    return _ok(_get_client().write("CreateDeploymentFromContainer", {"name": name, "server": server}))


def create_docker_registry_account(account: dict):
    """CreateDockerRegistryAccount.

    account fields: _id (dict), domain (str), username (str), token (str)
    """
    return _ok(_get_client().write("CreateDockerRegistryAccount", {"account": account}))


def create_git_provider_account(account: dict):
    """CreateGitProviderAccount.

    account fields: _id (dict), domain (str), https (bool), username (str), token (str)
    """
    return _ok(_get_client().write("CreateGitProviderAccount", {"account": account}))


def create_local_user(username: str, password: str):
    """CreateLocalUser."""
    return _ok(_get_client().write("CreateLocalUser", {"username": username, "password": password}))


def create_network(server: str, name: str):
    """CreateNetwork."""
    return _ok(_get_client().write("CreateNetwork", {"server": server, "name": name}))


def create_procedure(name: str, config: dict | None = None):
    """CreateProcedure.

    config fields: stages (list[dict]), schedule_format (Literal["English", "Cron"]), schedule (str), schedule_enabled (bool), schedule_timezone (str), schedule_alert (bool), failure_alert (bool), webhook_enabled (bool), webhook_secret (str)
    """
    params: dict = {"name": name}
    if config is not None:
        params["config"] = config
    return _ok(_get_client().write("CreateProcedure", params))


def create_repo(name: str, config: dict | None = None):
    """CreateRepo.

    config fields: server_id (str), builder_id (str), git_provider (str), git_https (bool), git_account (str), repo (str), branch (str), commit (str), path (str), webhook_enabled (bool), webhook_secret (str), on_clone (dict), on_pull (dict), links (list[str]), environment (str), ...
    """
    params: dict = {"name": name}
    if config is not None:
        params["config"] = config
    return _ok(_get_client().write("CreateRepo", params))


def create_repo_webhook(repo: str, action: Literal["Clone", "Pull", "Build"]):
    """CreateRepoWebhook."""
    return _ok(_get_client().write("CreateRepoWebhook", {"repo": repo, "action": action}))


def create_resource_sync(name: str, config: dict | None = None):
    """CreateResourceSync.

    config fields: linked_repo (str), git_provider (str), git_https (bool), repo (str), branch (str), commit (str), git_account (str), webhook_enabled (bool), webhook_secret (str), files_on_host (bool), resource_path (list[str]), managed (bool), delete (bool), include_resources (bool), match_tags (list[str]), ...
    """
    params: dict = {"name": name}
    if config is not None:
        params["config"] = config
    return _ok(_get_client().write("CreateResourceSync", params))


def create_server(name: str, config: dict | None = None):
    """CreateServer.

    config fields: address (str), external_address (str), region (str), enabled (bool), timeout_seconds (int), passkey (str), ignore_mounts (list[str]), stats_monitoring (bool), auto_prune (bool), links (list[str]), send_unreachable_alerts (bool), send_cpu_alerts (bool), send_mem_alerts (bool), send_disk_alerts (bool), send_version_mismatch_alerts (bool), ...
    """
    params: dict = {"name": name}
    if config is not None:
        params["config"] = config
    return _ok(_get_client().write("CreateServer", params))


def create_service_user(username: str, description: str):
    """CreateServiceUser."""
    return _ok(_get_client().write("CreateServiceUser", {"username": username, "description": description}))


def create_stack(name: str, config: dict | None = None):
    """CreateStack.

    config fields: server_id (str), links (list[str]), project_name (str), auto_pull (bool), run_build (bool), poll_for_updates (bool), auto_update (bool), auto_update_all_services (bool), destroy_before_deploy (bool), skip_secret_interp (bool), linked_repo (str), git_provider (str), git_https (bool), git_account (str), repo (str), ...
    """
    params: dict = {"name": name}
    if config is not None:
        params["config"] = config
    return _ok(_get_client().write("CreateStack", params))


def create_stack_webhook(stack: str, action: Literal["Refresh", "Deploy"]):
    """CreateStackWebhook."""
    return _ok(_get_client().write("CreateStackWebhook", {"stack": stack, "action": action}))


def create_sync_webhook(sync: str, action: Literal["Refresh", "Sync"]):
    """CreateSyncWebhook."""
    return _ok(_get_client().write("CreateSyncWebhook", {"sync": sync, "action": action}))


def create_tag(name: str, color: Literal["LightSlate", "Slate", "DarkSlate", "LightRed", "Red", "DarkRed", "LightOrange", "Orange", "DarkOrange", "LightAmber", "Amber", "DarkAmber", "LightYellow", "Yellow", "DarkYellow", "LightLime", "Lime", "DarkLime", "LightGreen", "Green", "DarkGreen", "LightEmerald", "Emerald", "DarkEmerald", "LightTeal", "Teal", "DarkTeal", "LightCyan", "Cyan", "DarkCyan", "LightSky", "Sky", "DarkSky", "LightBlue", "Blue", "DarkBlue", "LightIndigo", "Indigo", "DarkIndigo", "LightViolet", "Violet", "DarkViolet", "LightPurple", "Purple", "DarkPurple", "LightFuchsia", "Fuchsia", "DarkFuchsia", "LightPink", "Pink", "DarkPink", "LightRose", "Rose", "DarkRose"] | None = None):
    """CreateTag."""
    params: dict = {"name": name}
    if color is not None:
        params["color"] = color
    return _ok(_get_client().write("CreateTag", params))


def create_terminal(server: str, name: str, command: str, recreate: Literal["Never", "Always", "DifferentCommand"] | None = None):
    """CreateTerminal."""
    params: dict = {"server": server, "name": name, "command": command}
    if recreate is not None:
        params["recreate"] = recreate
    return _ok(_get_client().write("CreateTerminal", params))


def create_user_group(name: str):
    """CreateUserGroup."""
    return _ok(_get_client().write("CreateUserGroup", {"name": name}))


def create_variable(name: str, value: str | None = None, description: str | None = None, is_secret: bool | None = None):
    """CreateVariable."""
    params: dict = {"name": name}
    if value is not None:
        params["value"] = value
    if description is not None:
        params["description"] = description
    if is_secret is not None:
        params["is_secret"] = is_secret
    return _ok(_get_client().write("CreateVariable", params))


def delete_action(id: str):
    """DeleteAction."""
    return _ok(_get_client().write("DeleteAction", {"id": id}))


def delete_alerter(id: str):
    """DeleteAlerter."""
    return _ok(_get_client().write("DeleteAlerter", {"id": id}))


def delete_all_terminals(server: str):
    """DeleteAllTerminals."""
    return _ok(_get_client().write("DeleteAllTerminals", {"server": server}))


def delete_api_key_for_service_user(key: str):
    """DeleteApiKeyForServiceUser."""
    return _ok(_get_client().write("DeleteApiKeyForServiceUser", {"key": key}))


def delete_build(id: str):
    """DeleteBuild."""
    return _ok(_get_client().write("DeleteBuild", {"id": id}))


def delete_builder(id: str):
    """DeleteBuilder."""
    return _ok(_get_client().write("DeleteBuilder", {"id": id}))


def delete_build_webhook(build: str):
    """DeleteBuildWebhook."""
    return _ok(_get_client().write("DeleteBuildWebhook", {"build": build}))


def delete_deployment(id: str):
    """DeleteDeployment."""
    return _ok(_get_client().write("DeleteDeployment", {"id": id}))


def delete_docker_registry_account(id: str):
    """DeleteDockerRegistryAccount."""
    return _ok(_get_client().write("DeleteDockerRegistryAccount", {"id": id}))


def delete_git_provider_account(id: str):
    """DeleteGitProviderAccount."""
    return _ok(_get_client().write("DeleteGitProviderAccount", {"id": id}))


def delete_procedure(id: str):
    """DeleteProcedure."""
    return _ok(_get_client().write("DeleteProcedure", {"id": id}))


def delete_repo(id: str):
    """DeleteRepo."""
    return _ok(_get_client().write("DeleteRepo", {"id": id}))


def delete_repo_webhook(repo: str, action: Literal["Clone", "Pull", "Build"]):
    """DeleteRepoWebhook."""
    return _ok(_get_client().write("DeleteRepoWebhook", {"repo": repo, "action": action}))


def delete_resource_sync(id: str):
    """DeleteResourceSync."""
    return _ok(_get_client().write("DeleteResourceSync", {"id": id}))


def delete_server(id: str):
    """DeleteServer."""
    return _ok(_get_client().write("DeleteServer", {"id": id}))


def delete_stack(id: str):
    """DeleteStack."""
    return _ok(_get_client().write("DeleteStack", {"id": id}))


def delete_stack_webhook(stack: str, action: Literal["Refresh", "Deploy"]):
    """DeleteStackWebhook."""
    return _ok(_get_client().write("DeleteStackWebhook", {"stack": stack, "action": action}))


def delete_sync_webhook(sync: str, action: Literal["Refresh", "Sync"]):
    """DeleteSyncWebhook."""
    return _ok(_get_client().write("DeleteSyncWebhook", {"sync": sync, "action": action}))


def delete_tag(id: str):
    """DeleteTag."""
    return _ok(_get_client().write("DeleteTag", {"id": id}))


def delete_terminal(server: str, terminal: str):
    """DeleteTerminal."""
    return _ok(_get_client().write("DeleteTerminal", {"server": server, "terminal": terminal}))


def delete_user(user: str):
    """DeleteUser."""
    return _ok(_get_client().write("DeleteUser", {"user": user}))


def delete_user_group(id: str):
    """DeleteUserGroup."""
    return _ok(_get_client().write("DeleteUserGroup", {"id": id}))


def delete_variable(name: str):
    """DeleteVariable."""
    return _ok(_get_client().write("DeleteVariable", {"name": name}))


def refresh_build_cache(build: str):
    """RefreshBuildCache."""
    return _ok(_get_client().write("RefreshBuildCache", {"build": build}))


def refresh_repo_cache(repo: str):
    """RefreshRepoCache."""
    return _ok(_get_client().write("RefreshRepoCache", {"repo": repo}))


def refresh_resource_sync_pending(sync: str):
    """RefreshResourceSyncPending."""
    return _ok(_get_client().write("RefreshResourceSyncPending", {"sync": sync}))


def refresh_stack_cache(stack: str):
    """RefreshStackCache."""
    return _ok(_get_client().write("RefreshStackCache", {"stack": stack}))


def remove_user_from_user_group(user_group: str, user: str):
    """RemoveUserFromUserGroup."""
    return _ok(_get_client().write("RemoveUserFromUserGroup", {"user_group": user_group, "user": user}))


def rename_action(id: str, name: str):
    """RenameAction."""
    return _ok(_get_client().write("RenameAction", {"id": id, "name": name}))


def rename_alerter(id: str, name: str):
    """RenameAlerter."""
    return _ok(_get_client().write("RenameAlerter", {"id": id, "name": name}))


def rename_build(id: str, name: str):
    """RenameBuild."""
    return _ok(_get_client().write("RenameBuild", {"id": id, "name": name}))


def rename_builder(id: str, name: str):
    """RenameBuilder."""
    return _ok(_get_client().write("RenameBuilder", {"id": id, "name": name}))


def rename_deployment(id: str, name: str):
    """RenameDeployment."""
    return _ok(_get_client().write("RenameDeployment", {"id": id, "name": name}))


def rename_procedure(id: str, name: str):
    """RenameProcedure."""
    return _ok(_get_client().write("RenameProcedure", {"id": id, "name": name}))


def rename_repo(id: str, name: str):
    """RenameRepo."""
    return _ok(_get_client().write("RenameRepo", {"id": id, "name": name}))


def rename_resource_sync(id: str, name: str):
    """RenameResourceSync."""
    return _ok(_get_client().write("RenameResourceSync", {"id": id, "name": name}))


def rename_server(id: str, name: str):
    """RenameServer."""
    return _ok(_get_client().write("RenameServer", {"id": id, "name": name}))


def rename_stack(id: str, name: str):
    """RenameStack."""
    return _ok(_get_client().write("RenameStack", {"id": id, "name": name}))


def rename_tag(id: str, name: str):
    """RenameTag."""
    return _ok(_get_client().write("RenameTag", {"id": id, "name": name}))


def rename_user_group(id: str, name: str):
    """RenameUserGroup."""
    return _ok(_get_client().write("RenameUserGroup", {"id": id, "name": name}))


def set_everyone_user_group(user_group: str, everyone: bool):
    """SetEveryoneUserGroup."""
    return _ok(_get_client().write("SetEveryoneUserGroup", {"user_group": user_group, "everyone": everyone}))


def set_users_in_user_group(user_group: str, users: list[str]):
    """SetUsersInUserGroup."""
    return _ok(_get_client().write("SetUsersInUserGroup", {"user_group": user_group, "users": users}))


def update_action(id: str, config: dict):
    """UpdateAction.

    config fields: run_at_startup (bool), schedule_format (Literal["English", "Cron"]), schedule (str), schedule_enabled (bool), schedule_timezone (str), schedule_alert (bool), failure_alert (bool), webhook_enabled (bool), webhook_secret (str), reload_deno_deps (bool), file_contents (str), arguments_format (Literal["key_value", "toml", "yaml", "json"]), arguments (str)
    """
    return _ok(_get_client().write("UpdateAction", {"id": id, "config": config}))


def update_alerter(id: str, config: dict):
    """UpdateAlerter.

    config fields: enabled (bool), endpoint (dict), alert_types (list[Literal["Custom", "None", "Test", "ServerUnreachable", "ServerCpu", "ServerMem", "ServerDisk", "ServerVersionMismatch", "ContainerStateChange", "DeploymentImageUpdateAvailable", "DeploymentAutoUpdated", "StackStateChange", "StackImageUpdateAvailable", "StackAutoUpdated", "AwsBuilderTerminationFailed", "ResourceSyncPendingUpdates", "BuildFailed", "RepoBuildFailed", "ProcedureFailed", "ActionFailed", "ScheduleRun"]]), resources (list[dict]), except_resources (list[dict]), maintenance_windows (list[dict])
    """
    return _ok(_get_client().write("UpdateAlerter", {"id": id, "config": config}))


def update_build(id: str, config: dict):
    """UpdateBuild.

    config fields: builder_id (str), version (dict), auto_increment_version (bool), image_name (str), image_tag (str), include_latest_tag (bool), include_version_tags (bool), include_commit_tag (bool), links (list[str]), linked_repo (str), git_provider (str), git_https (bool), git_account (str), repo (str), branch (str), ...
    """
    return _ok(_get_client().write("UpdateBuild", {"id": id, "config": config}))


def update_builder(id: str, config: dict):
    """UpdateBuilder."""
    return _ok(_get_client().write("UpdateBuilder", {"id": id, "config": config}))


def update_deployment(id: str, config: dict):
    """UpdateDeployment.

    config fields: server_id (str), image (dict), image_registry_account (str), skip_secret_interp (bool), redeploy_on_build (bool), poll_for_updates (bool), auto_update (bool), send_alerts (bool), links (list[str]), network (str), restart (Literal["no", "on-failure", "always", "unless-stopped"]), command (str), termination_signal (Literal["SIGHUP", "SIGINT", "SIGQUIT", "SIGTERM"]), termination_timeout (int), extra_args (list[str]), ...
    """
    return _ok(_get_client().write("UpdateDeployment", {"id": id, "config": config}))


def update_docker_registry_account(id: str, account: dict):
    """UpdateDockerRegistryAccount.

    account fields: _id (dict), domain (str), username (str), token (str)
    """
    return _ok(_get_client().write("UpdateDockerRegistryAccount", {"id": id, "account": account}))


def update_git_provider_account(id: str, account: dict):
    """UpdateGitProviderAccount.

    account fields: _id (dict), domain (str), https (bool), username (str), token (str)
    """
    return _ok(_get_client().write("UpdateGitProviderAccount", {"id": id, "account": account}))


def update_permission_on_resource_type(user_target_type: Literal["User", "UserGroup"], user_target_id: str, resource_type: Literal["System", "Server", "Stack", "Deployment", "Build", "Repo", "Procedure", "Action", "Builder", "Alerter", "ResourceSync"], permission: dict):
    """UpdatePermissionOnResourceType."""
    params: dict = {"resource_type": resource_type, "permission": permission}
    params["user_target"] = {"type": user_target_type, "id": user_target_id}
    return _ok(_get_client().write("UpdatePermissionOnResourceType", params or None))


def update_permission_on_target(user_target_type: Literal["User", "UserGroup"], user_target_id: str, resource_target_type: Literal["System", "Server", "Stack", "Deployment", "Build", "Repo", "Procedure", "Action", "Builder", "Alerter", "ResourceSync"], resource_target_id: str, permission: dict):
    """UpdatePermissionOnTarget."""
    params: dict = {"permission": permission}
    params["user_target"] = {"type": user_target_type, "id": user_target_id}
    params["resource_target"] = {"type": resource_target_type, "id": resource_target_id}
    return _ok(_get_client().write("UpdatePermissionOnTarget", params or None))


def update_procedure(id: str, config: dict):
    """UpdateProcedure.

    config fields: stages (list[dict]), schedule_format (Literal["English", "Cron"]), schedule (str), schedule_enabled (bool), schedule_timezone (str), schedule_alert (bool), failure_alert (bool), webhook_enabled (bool), webhook_secret (str)
    """
    return _ok(_get_client().write("UpdateProcedure", {"id": id, "config": config}))


def update_repo(id: str, config: dict):
    """UpdateRepo.

    config fields: server_id (str), builder_id (str), git_provider (str), git_https (bool), git_account (str), repo (str), branch (str), commit (str), path (str), webhook_enabled (bool), webhook_secret (str), on_clone (dict), on_pull (dict), links (list[str]), environment (str), ...
    """
    return _ok(_get_client().write("UpdateRepo", {"id": id, "config": config}))


def update_resource_meta(target_type: Literal["System", "Server", "Stack", "Deployment", "Build", "Repo", "Procedure", "Action", "Builder", "Alerter", "ResourceSync"], target_id: str, description: str | None = None, template: bool | None = None, tags: list[str] | None = None):
    """UpdateResourceMeta."""
    params: dict = {}
    if description is not None:
        params["description"] = description
    if template is not None:
        params["template"] = template
    if tags is not None:
        params["tags"] = tags
    params["target"] = {"type": target_type, "id": target_id}
    return _ok(_get_client().write("UpdateResourceMeta", params or None))


def update_resource_sync(id: str, config: dict):
    """UpdateResourceSync.

    config fields: linked_repo (str), git_provider (str), git_https (bool), repo (str), branch (str), commit (str), git_account (str), webhook_enabled (bool), webhook_secret (str), files_on_host (bool), resource_path (list[str]), managed (bool), delete (bool), include_resources (bool), match_tags (list[str]), ...
    """
    return _ok(_get_client().write("UpdateResourceSync", {"id": id, "config": config}))


def update_server(id: str, config: dict):
    """UpdateServer.

    config fields: address (str), external_address (str), region (str), enabled (bool), timeout_seconds (int), passkey (str), ignore_mounts (list[str]), stats_monitoring (bool), auto_prune (bool), links (list[str]), send_unreachable_alerts (bool), send_cpu_alerts (bool), send_mem_alerts (bool), send_disk_alerts (bool), send_version_mismatch_alerts (bool), ...
    """
    return _ok(_get_client().write("UpdateServer", {"id": id, "config": config}))


def update_service_user_description(username: str, description: str):
    """UpdateServiceUserDescription."""
    return _ok(_get_client().write("UpdateServiceUserDescription", {"username": username, "description": description}))


def update_stack(id: str, config: dict):
    """UpdateStack.

    config fields: server_id (str), links (list[str]), project_name (str), auto_pull (bool), run_build (bool), poll_for_updates (bool), auto_update (bool), auto_update_all_services (bool), destroy_before_deploy (bool), skip_secret_interp (bool), linked_repo (str), git_provider (str), git_https (bool), git_account (str), repo (str), ...
    """
    return _ok(_get_client().write("UpdateStack", {"id": id, "config": config}))


def update_tag_color(tag: str, color: Literal["LightSlate", "Slate", "DarkSlate", "LightRed", "Red", "DarkRed", "LightOrange", "Orange", "DarkOrange", "LightAmber", "Amber", "DarkAmber", "LightYellow", "Yellow", "DarkYellow", "LightLime", "Lime", "DarkLime", "LightGreen", "Green", "DarkGreen", "LightEmerald", "Emerald", "DarkEmerald", "LightTeal", "Teal", "DarkTeal", "LightCyan", "Cyan", "DarkCyan", "LightSky", "Sky", "DarkSky", "LightBlue", "Blue", "DarkBlue", "LightIndigo", "Indigo", "DarkIndigo", "LightViolet", "Violet", "DarkViolet", "LightPurple", "Purple", "DarkPurple", "LightFuchsia", "Fuchsia", "DarkFuchsia", "LightPink", "Pink", "DarkPink", "LightRose", "Rose", "DarkRose"]):
    """UpdateTagColor."""
    return _ok(_get_client().write("UpdateTagColor", {"tag": tag, "color": color}))


def update_user_admin(user_id: str, admin: bool):
    """UpdateUserAdmin."""
    return _ok(_get_client().write("UpdateUserAdmin", {"user_id": user_id, "admin": admin}))


def update_user_base_permissions(user_id: str, enabled: bool | None = None, create_servers: bool | None = None, create_builds: bool | None = None):
    """UpdateUserBasePermissions."""
    params: dict = {"user_id": user_id}
    if enabled is not None:
        params["enabled"] = enabled
    if create_servers is not None:
        params["create_servers"] = create_servers
    if create_builds is not None:
        params["create_builds"] = create_builds
    return _ok(_get_client().write("UpdateUserBasePermissions", params))


def update_user_password(password: str):
    """UpdateUserPassword."""
    return _ok(_get_client().write("UpdateUserPassword", {"password": password}))


def update_user_username(username: str):
    """UpdateUserUsername."""
    return _ok(_get_client().write("UpdateUserUsername", {"username": username}))


def update_variable_description(name: str, description: str):
    """UpdateVariableDescription."""
    return _ok(_get_client().write("UpdateVariableDescription", {"name": name, "description": description}))


def update_variable_is_secret(name: str, is_secret: bool):
    """UpdateVariableIsSecret."""
    return _ok(_get_client().write("UpdateVariableIsSecret", {"name": name, "is_secret": is_secret}))


def update_variable_value(name: str, value: str):
    """UpdateVariableValue."""
    return _ok(_get_client().write("UpdateVariableValue", {"name": name, "value": value}))


def write_build_file_contents(build: str, contents: str):
    """WriteBuildFileContents."""
    return _ok(_get_client().write("WriteBuildFileContents", {"build": build, "contents": contents}))


def write_stack_file_contents(stack: str, file_path: str, contents: str):
    """WriteStackFileContents."""
    return _ok(_get_client().write("WriteStackFileContents", {"stack": stack, "file_path": file_path, "contents": contents}))


def write_sync_file_contents(sync: str, resource_path: str, file_path: str, contents: str):
    """WriteSyncFileContents."""
    return _ok(_get_client().write("WriteSyncFileContents", {"sync": sync, "resource_path": resource_path, "file_path": file_path, "contents": contents}))


# ── execute ─────────────────────────────────────────────────────────────

def backup_core_database():
    """BackupCoreDatabase."""
    return _ok(_get_client().execute("BackupCoreDatabase"))


def batch_build_repo(pattern: str):
    """BatchBuildRepo."""
    return _ok(_get_client().execute("BatchBuildRepo", {"pattern": pattern}))


def batch_clone_repo(pattern: str):
    """BatchCloneRepo."""
    return _ok(_get_client().execute("BatchCloneRepo", {"pattern": pattern}))


def batch_deploy(pattern: str):
    """BatchDeploy."""
    return _ok(_get_client().execute("BatchDeploy", {"pattern": pattern}))


def batch_deploy_stack(pattern: str):
    """BatchDeployStack."""
    return _ok(_get_client().execute("BatchDeployStack", {"pattern": pattern}))


def batch_deploy_stack_if_changed(pattern: str):
    """BatchDeployStackIfChanged."""
    return _ok(_get_client().execute("BatchDeployStackIfChanged", {"pattern": pattern}))


def batch_destroy_deployment(pattern: str):
    """BatchDestroyDeployment."""
    return _ok(_get_client().execute("BatchDestroyDeployment", {"pattern": pattern}))


def batch_destroy_stack(pattern: str):
    """BatchDestroyStack."""
    return _ok(_get_client().execute("BatchDestroyStack", {"pattern": pattern}))


def batch_pull_repo(pattern: str):
    """BatchPullRepo."""
    return _ok(_get_client().execute("BatchPullRepo", {"pattern": pattern}))


def batch_pull_stack(pattern: str):
    """BatchPullStack."""
    return _ok(_get_client().execute("BatchPullStack", {"pattern": pattern}))


def batch_run_action(pattern: str):
    """BatchRunAction."""
    return _ok(_get_client().execute("BatchRunAction", {"pattern": pattern}))


def batch_run_build(pattern: str):
    """BatchRunBuild."""
    return _ok(_get_client().execute("BatchRunBuild", {"pattern": pattern}))


def batch_run_procedure(pattern: str):
    """BatchRunProcedure."""
    return _ok(_get_client().execute("BatchRunProcedure", {"pattern": pattern}))


def build_repo(repo: str):
    """BuildRepo."""
    return _ok(_get_client().execute("BuildRepo", {"repo": repo}))


def cancel_build(build: str):
    """CancelBuild."""
    return _ok(_get_client().execute("CancelBuild", {"build": build}))


def cancel_repo_build(repo: str):
    """CancelRepoBuild."""
    return _ok(_get_client().execute("CancelRepoBuild", {"repo": repo}))


def clear_repo_cache():
    """ClearRepoCache."""
    return _ok(_get_client().execute("ClearRepoCache"))


def clone_repo(repo: str):
    """CloneRepo."""
    return _ok(_get_client().execute("CloneRepo", {"repo": repo}))


def delete_image(server: str, name: str):
    """DeleteImage."""
    return _ok(_get_client().execute("DeleteImage", {"server": server, "name": name}))


def delete_network(server: str, name: str):
    """DeleteNetwork."""
    return _ok(_get_client().execute("DeleteNetwork", {"server": server, "name": name}))


def delete_volume(server: str, name: str):
    """DeleteVolume."""
    return _ok(_get_client().execute("DeleteVolume", {"server": server, "name": name}))


def deploy(deployment: str, stop_signal: Literal["SIGHUP", "SIGINT", "SIGQUIT", "SIGTERM"] | None = None, stop_time: int | None = None):
    """Deploy."""
    params: dict = {"deployment": deployment}
    if stop_signal is not None:
        params["stop_signal"] = stop_signal
    if stop_time is not None:
        params["stop_time"] = stop_time
    return _ok(_get_client().execute("Deploy", params))


def deploy_stack(stack: str, services: list[str] | None = None, stop_time: int | None = None):
    """DeployStack."""
    params: dict = {"stack": stack}
    if services is not None:
        params["services"] = services
    if stop_time is not None:
        params["stop_time"] = stop_time
    return _ok(_get_client().execute("DeployStack", params))


def deploy_stack_if_changed(stack: str, stop_time: int | None = None):
    """DeployStackIfChanged."""
    params: dict = {"stack": stack}
    if stop_time is not None:
        params["stop_time"] = stop_time
    return _ok(_get_client().execute("DeployStackIfChanged", params))


def destroy_container(server: str, container: str, signal: Literal["SIGHUP", "SIGINT", "SIGQUIT", "SIGTERM"] | None = None, time: int | None = None):
    """DestroyContainer."""
    params: dict = {"server": server, "container": container}
    if signal is not None:
        params["signal"] = signal
    if time is not None:
        params["time"] = time
    return _ok(_get_client().execute("DestroyContainer", params))


def destroy_deployment(deployment: str, signal: Literal["SIGHUP", "SIGINT", "SIGQUIT", "SIGTERM"] | None = None, time: int | None = None):
    """DestroyDeployment."""
    params: dict = {"deployment": deployment}
    if signal is not None:
        params["signal"] = signal
    if time is not None:
        params["time"] = time
    return _ok(_get_client().execute("DestroyDeployment", params))


def destroy_stack(stack: str, services: list[str] | None = None, remove_orphans: bool | None = None, stop_time: int | None = None):
    """DestroyStack."""
    params: dict = {"stack": stack}
    if services is not None:
        params["services"] = services
    if remove_orphans is not None:
        params["remove_orphans"] = remove_orphans
    if stop_time is not None:
        params["stop_time"] = stop_time
    return _ok(_get_client().execute("DestroyStack", params))


def global_auto_update():
    """GlobalAutoUpdate."""
    return _ok(_get_client().execute("GlobalAutoUpdate"))


def pause_all_containers(server: str):
    """PauseAllContainers."""
    return _ok(_get_client().execute("PauseAllContainers", {"server": server}))


def pause_container(server: str, container: str):
    """PauseContainer."""
    return _ok(_get_client().execute("PauseContainer", {"server": server, "container": container}))


def pause_deployment(deployment: str):
    """PauseDeployment."""
    return _ok(_get_client().execute("PauseDeployment", {"deployment": deployment}))


def pause_stack(stack: str, services: list[str] | None = None):
    """PauseStack."""
    params: dict = {"stack": stack}
    if services is not None:
        params["services"] = services
    return _ok(_get_client().execute("PauseStack", params))


def prune_buildx(server: str):
    """PruneBuildx."""
    return _ok(_get_client().execute("PruneBuildx", {"server": server}))


def prune_containers(server: str):
    """PruneContainers."""
    return _ok(_get_client().execute("PruneContainers", {"server": server}))


def prune_docker_builders(server: str):
    """PruneDockerBuilders."""
    return _ok(_get_client().execute("PruneDockerBuilders", {"server": server}))


def prune_images(server: str):
    """PruneImages."""
    return _ok(_get_client().execute("PruneImages", {"server": server}))


def prune_networks(server: str):
    """PruneNetworks."""
    return _ok(_get_client().execute("PruneNetworks", {"server": server}))


def prune_system(server: str):
    """PruneSystem."""
    return _ok(_get_client().execute("PruneSystem", {"server": server}))


def prune_volumes(server: str):
    """PruneVolumes."""
    return _ok(_get_client().execute("PruneVolumes", {"server": server}))


def pull_deployment(deployment: str):
    """PullDeployment."""
    return _ok(_get_client().execute("PullDeployment", {"deployment": deployment}))


def pull_repo(repo: str):
    """PullRepo."""
    return _ok(_get_client().execute("PullRepo", {"repo": repo}))


def pull_stack(stack: str, services: list[str] | None = None):
    """PullStack."""
    params: dict = {"stack": stack}
    if services is not None:
        params["services"] = services
    return _ok(_get_client().execute("PullStack", params))


def restart_all_containers(server: str):
    """RestartAllContainers."""
    return _ok(_get_client().execute("RestartAllContainers", {"server": server}))


def restart_container(server: str, container: str):
    """RestartContainer."""
    return _ok(_get_client().execute("RestartContainer", {"server": server, "container": container}))


def restart_deployment(deployment: str):
    """RestartDeployment."""
    return _ok(_get_client().execute("RestartDeployment", {"deployment": deployment}))


def restart_stack(stack: str, services: list[str] | None = None):
    """RestartStack."""
    params: dict = {"stack": stack}
    if services is not None:
        params["services"] = services
    return _ok(_get_client().execute("RestartStack", params))


def run_action(action: str, args: dict | None = None):
    """RunAction."""
    params: dict = {"action": action}
    if args is not None:
        params["args"] = args
    return _ok(_get_client().execute("RunAction", params))


def run_build(build: str):
    """RunBuild."""
    return _ok(_get_client().execute("RunBuild", {"build": build}))


def run_procedure(procedure: str):
    """RunProcedure."""
    return _ok(_get_client().execute("RunProcedure", {"procedure": procedure}))


def run_stack_service(stack: str, service: str, command: list[str] | None = None, no_tty: bool | None = None, no_deps: bool | None = None, detach: bool | None = None, service_ports: bool | None = None, env: dict | None = None, workdir: str | None = None, user: str | None = None, entrypoint: str | None = None, pull: bool | None = None):
    """RunStackService."""
    params: dict = {"stack": stack, "service": service}
    if command is not None:
        params["command"] = command
    if no_tty is not None:
        params["no_tty"] = no_tty
    if no_deps is not None:
        params["no_deps"] = no_deps
    if detach is not None:
        params["detach"] = detach
    if service_ports is not None:
        params["service_ports"] = service_ports
    if env is not None:
        params["env"] = env
    if workdir is not None:
        params["workdir"] = workdir
    if user is not None:
        params["user"] = user
    if entrypoint is not None:
        params["entrypoint"] = entrypoint
    if pull is not None:
        params["pull"] = pull
    return _ok(_get_client().execute("RunStackService", params))


def run_sync(sync: str, resource_type: Literal["System", "Server", "Stack", "Deployment", "Build", "Repo", "Procedure", "Action", "Builder", "Alerter", "ResourceSync"] | None = None, resources: list[str] | None = None):
    """RunSync."""
    params: dict = {"sync": sync}
    if resource_type is not None:
        params["resource_type"] = resource_type
    if resources is not None:
        params["resources"] = resources
    return _ok(_get_client().execute("RunSync", params))


def send_alert(message: str, level: Literal["OK", "WARNING", "CRITICAL"] | None = None, details: str | None = None, alerters: list[str] | None = None):
    """SendAlert."""
    params: dict = {"message": message}
    if level is not None:
        params["level"] = level
    if details is not None:
        params["details"] = details
    if alerters is not None:
        params["alerters"] = alerters
    return _ok(_get_client().execute("SendAlert", params))


def start_all_containers(server: str):
    """StartAllContainers."""
    return _ok(_get_client().execute("StartAllContainers", {"server": server}))


def start_container(server: str, container: str):
    """StartContainer."""
    return _ok(_get_client().execute("StartContainer", {"server": server, "container": container}))


def start_deployment(deployment: str):
    """StartDeployment."""
    return _ok(_get_client().execute("StartDeployment", {"deployment": deployment}))


def start_stack(stack: str, services: list[str] | None = None):
    """StartStack."""
    params: dict = {"stack": stack}
    if services is not None:
        params["services"] = services
    return _ok(_get_client().execute("StartStack", params))


def stop_all_containers(server: str):
    """StopAllContainers."""
    return _ok(_get_client().execute("StopAllContainers", {"server": server}))


def stop_container(server: str, container: str, signal: Literal["SIGHUP", "SIGINT", "SIGQUIT", "SIGTERM"] | None = None, time: int | None = None):
    """StopContainer."""
    params: dict = {"server": server, "container": container}
    if signal is not None:
        params["signal"] = signal
    if time is not None:
        params["time"] = time
    return _ok(_get_client().execute("StopContainer", params))


def stop_deployment(deployment: str, signal: Literal["SIGHUP", "SIGINT", "SIGQUIT", "SIGTERM"] | None = None, time: int | None = None):
    """StopDeployment."""
    params: dict = {"deployment": deployment}
    if signal is not None:
        params["signal"] = signal
    if time is not None:
        params["time"] = time
    return _ok(_get_client().execute("StopDeployment", params))


def stop_stack(stack: str, stop_time: int | None = None, services: list[str] | None = None):
    """StopStack."""
    params: dict = {"stack": stack}
    if stop_time is not None:
        params["stop_time"] = stop_time
    if services is not None:
        params["services"] = services
    return _ok(_get_client().execute("StopStack", params))


def test_alerter(alerter: str):
    """TestAlerter."""
    return _ok(_get_client().execute("TestAlerter", {"alerter": alerter}))


def unpause_all_containers(server: str):
    """UnpauseAllContainers."""
    return _ok(_get_client().execute("UnpauseAllContainers", {"server": server}))


def unpause_container(server: str, container: str):
    """UnpauseContainer."""
    return _ok(_get_client().execute("UnpauseContainer", {"server": server, "container": container}))


def unpause_deployment(deployment: str):
    """UnpauseDeployment."""
    return _ok(_get_client().execute("UnpauseDeployment", {"deployment": deployment}))


def unpause_stack(stack: str, services: list[str] | None = None):
    """UnpauseStack."""
    params: dict = {"stack": stack}
    if services is not None:
        params["services"] = services
    return _ok(_get_client().execute("UnpauseStack", params))
