# GENERATED by codegen/generate.ts — DO NOT EDIT
from __future__ import annotations

from ._helpers import _ok, _get_client


# ── read ────────────────────────────────────────────────────────────────

def export_all_resources_to_toml(include_resources: bool, tags: list[str] | None = None, include_variables: bool | None = None, include_user_groups: bool | None = None):
    """ExportAllResourcesToToml.

    include_resources: Whether to include any resources (servers, stacks, etc.)
    tags: Filter resources by tag.
    include_variables: Whether to include variables in the exported contents.
    include_user_groups: Whether to include user groups in the exported contents.
    """
    params: dict = {"include_resources": include_resources}
    if tags is not None:
        params["tags"] = tags
    if include_variables is not None:
        params["include_variables"] = include_variables
    if include_user_groups is not None:
        params["include_user_groups"] = include_user_groups
    return _ok(_get_client().read("ExportAllResourcesToToml", params))


def export_resources_to_toml(targets: list[dict] | None = None, user_groups: list[str] | None = None, include_variables: bool | None = None):
    """ExportResourcesToToml.

    targets: The targets to include in the export.
    user_groups: The user group names or ids to include in the export.
    include_variables: Whether to include variables
    """
    params: dict = {}
    if targets is not None:
        params["targets"] = targets
    if user_groups is not None:
        params["user_groups"] = user_groups
    if include_variables is not None:
        params["include_variables"] = include_variables
    return _ok(_get_client().read("ExportResourcesToToml", params or None))


def find_user(user: str):
    """FindUser.

    user: Id or username
    """
    return _ok(_get_client().read("FindUser", {"user": user}))


def get_action(action: str):
    """GetAction.

    action: Id or name
    """
    return _ok(_get_client().read("GetAction", {"action": action}))


def get_action_action_state(action: str):
    """GetActionActionState.

    action: Id or name
    """
    return _ok(_get_client().read("GetActionActionState", {"action": action}))


def get_actions_summary():
    """GetActionsSummary."""
    return _ok(_get_client().read("GetActionsSummary"))


def get_alert(id: str):
    """GetAlert."""
    return _ok(_get_client().read("GetAlert", {"id": id}))


def get_alerter(alerter: str):
    """GetAlerter.

    alerter: Id or name
    """
    return _ok(_get_client().read("GetAlerter", {"alerter": alerter}))


def get_alerters_summary():
    """GetAlertersSummary."""
    return _ok(_get_client().read("GetAlertersSummary"))


def get_build(build: str):
    """GetBuild.

    build: Id or name
    """
    return _ok(_get_client().read("GetBuild", {"build": build}))


def get_build_action_state(build: str):
    """GetBuildActionState.

    build: Id or name
    """
    return _ok(_get_client().read("GetBuildActionState", {"build": build}))


def get_builder(builder: str):
    """GetBuilder.

    builder: Id or name
    """
    return _ok(_get_client().read("GetBuilder", {"builder": builder}))


def get_builders_summary():
    """GetBuildersSummary."""
    return _ok(_get_client().read("GetBuildersSummary"))


def get_build_monthly_stats(page: int | None = None):
    """GetBuildMonthlyStats.

    page: Query for older data by incrementing the page.
    """
    params: dict = {}
    if page is not None:
        params["page"] = page
    return _ok(_get_client().read("GetBuildMonthlyStats", params or None))


def get_builds_summary():
    """GetBuildsSummary."""
    return _ok(_get_client().read("GetBuildsSummary"))


def get_build_webhook_enabled(build: str):
    """GetBuildWebhookEnabled.

    build: Id or name
    """
    return _ok(_get_client().read("GetBuildWebhookEnabled", {"build": build}))


def get_container_log(server: str, container: str, tail: dict, timestamps: bool | None = None):
    """GetContainerLog.

    server: Id or name
    container: The container name
    tail: The number of lines of the log tail to include.
    timestamps: Enable `--timestamps`
    """
    params: dict = {"server": server, "container": container, "tail": tail}
    if timestamps is not None:
        params["timestamps"] = timestamps
    return _ok(_get_client().read("GetContainerLog", params))


def get_core_info():
    """GetCoreInfo."""
    return _ok(_get_client().read("GetCoreInfo"))


def get_deployment(deployment: str):
    """GetDeployment.

    deployment: Id or name
    """
    return _ok(_get_client().read("GetDeployment", {"deployment": deployment}))


def get_deployment_action_state(deployment: str):
    """GetDeploymentActionState.

    deployment: Id or name
    """
    return _ok(_get_client().read("GetDeploymentActionState", {"deployment": deployment}))


def get_deployment_container(deployment: str):
    """GetDeploymentContainer.

    deployment: Id or name
    """
    return _ok(_get_client().read("GetDeploymentContainer", {"deployment": deployment}))


def get_deployment_log(deployment: str, tail: dict, timestamps: bool | None = None):
    """GetDeploymentLog.

    deployment: Id or name
    tail: The number of lines of the log tail to include.
    timestamps: Enable `--timestamps`
    """
    params: dict = {"deployment": deployment, "tail": tail}
    if timestamps is not None:
        params["timestamps"] = timestamps
    return _ok(_get_client().read("GetDeploymentLog", params))


def get_deployments_summary():
    """GetDeploymentsSummary."""
    return _ok(_get_client().read("GetDeploymentsSummary"))


def get_deployment_stats(deployment: str):
    """GetDeploymentStats.

    deployment: Id or name
    """
    return _ok(_get_client().read("GetDeploymentStats", {"deployment": deployment}))


def get_docker_containers_summary():
    """GetDockerContainersSummary."""
    return _ok(_get_client().read("GetDockerContainersSummary"))


def get_docker_registry_account(id: str):
    """GetDockerRegistryAccount."""
    return _ok(_get_client().read("GetDockerRegistryAccount", {"id": id}))


def get_git_provider_account(id: str):
    """GetGitProviderAccount."""
    return _ok(_get_client().read("GetGitProviderAccount", {"id": id}))


def get_historical_server_stats(server: str, granularity: str, page: int | None = None):
    """GetHistoricalServerStats.

    server: Id or name
    granularity: The granularity of the data.
    page: Page of historical data. Default is 0, which is the most recent data.
    """
    params: dict = {"server": server, "granularity": granularity}
    if page is not None:
        params["page"] = page
    return _ok(_get_client().read("GetHistoricalServerStats", params))


def get_periphery_version(server: str):
    """GetPeripheryVersion.

    server: Id or name
    """
    return _ok(_get_client().read("GetPeripheryVersion", {"server": server}))


def get_permission(target: dict):
    """GetPermission.

    target: The target to get user permission on.
    """
    return _ok(_get_client().read("GetPermission", {"target": target}))


def get_procedure(procedure: str):
    """GetProcedure.

    procedure: Id or name
    """
    return _ok(_get_client().read("GetProcedure", {"procedure": procedure}))


def get_procedure_action_state(procedure: str):
    """GetProcedureActionState.

    procedure: Id or name
    """
    return _ok(_get_client().read("GetProcedureActionState", {"procedure": procedure}))


def get_procedures_summary():
    """GetProceduresSummary."""
    return _ok(_get_client().read("GetProceduresSummary"))


def get_repo(repo: str):
    """GetRepo.

    repo: Id or name
    """
    return _ok(_get_client().read("GetRepo", {"repo": repo}))


def get_repo_action_state(repo: str):
    """GetRepoActionState.

    repo: Id or name
    """
    return _ok(_get_client().read("GetRepoActionState", {"repo": repo}))


def get_repos_summary():
    """GetReposSummary."""
    return _ok(_get_client().read("GetReposSummary"))


def get_repo_webhooks_enabled(repo: str):
    """GetRepoWebhooksEnabled.

    repo: Id or name
    """
    return _ok(_get_client().read("GetRepoWebhooksEnabled", {"repo": repo}))


def get_resource_matching_container(server: str, container: str):
    """GetResourceMatchingContainer.

    server: Id or name
    container: The container name
    """
    return _ok(_get_client().read("GetResourceMatchingContainer", {"server": server, "container": container}))


def get_resource_sync(sync: str):
    """GetResourceSync.

    sync: Id or name
    """
    return _ok(_get_client().read("GetResourceSync", {"sync": sync}))


def get_resource_sync_action_state(sync: str):
    """GetResourceSyncActionState.

    sync: Id or name
    """
    return _ok(_get_client().read("GetResourceSyncActionState", {"sync": sync}))


def get_resource_syncs_summary():
    """GetResourceSyncsSummary."""
    return _ok(_get_client().read("GetResourceSyncsSummary"))


def get_server(server: str):
    """GetServer.

    server: Id or name
    """
    return _ok(_get_client().read("GetServer", {"server": server}))


def get_server_action_state(server: str):
    """GetServerActionState.

    server: Id or name
    """
    return _ok(_get_client().read("GetServerActionState", {"server": server}))


def get_servers_summary():
    """GetServersSummary."""
    return _ok(_get_client().read("GetServersSummary"))


def get_server_state(server: str):
    """GetServerState.

    server: Id or name
    """
    return _ok(_get_client().read("GetServerState", {"server": server}))


def get_stack(stack: str):
    """GetStack.

    stack: Id or name
    """
    return _ok(_get_client().read("GetStack", {"stack": stack}))


def get_stack_action_state(stack: str):
    """GetStackActionState.

    stack: Id or name
    """
    return _ok(_get_client().read("GetStackActionState", {"stack": stack}))


def get_stack_log(stack: str, services: list[str], tail: dict, timestamps: bool | None = None):
    """GetStackLog.

    stack: Id or name
    services: Filter the logs to only ones from specific services.
    tail: The number of lines of the log tail to include.
    timestamps: Enable `--timestamps`
    """
    params: dict = {"stack": stack, "services": services, "tail": tail}
    if timestamps is not None:
        params["timestamps"] = timestamps
    return _ok(_get_client().read("GetStackLog", params))


def get_stacks_summary():
    """GetStacksSummary."""
    return _ok(_get_client().read("GetStacksSummary"))


def get_stack_webhooks_enabled(stack: str):
    """GetStackWebhooksEnabled.

    stack: Id or name
    """
    return _ok(_get_client().read("GetStackWebhooksEnabled", {"stack": stack}))


def get_sync_webhooks_enabled(sync: str):
    """GetSyncWebhooksEnabled.

    sync: Id or name
    """
    return _ok(_get_client().read("GetSyncWebhooksEnabled", {"sync": sync}))


def get_system_information(server: str):
    """GetSystemInformation.

    server: Id or name
    """
    return _ok(_get_client().read("GetSystemInformation", {"server": server}))


def get_system_stats(server: str):
    """GetSystemStats.

    server: Id or name
    """
    return _ok(_get_client().read("GetSystemStats", {"server": server}))


def get_tag(tag: str):
    """GetTag.

    tag: Id or name
    """
    return _ok(_get_client().read("GetTag", {"tag": tag}))


def get_update(id: str):
    """GetUpdate.

    id: The update id.
    """
    return _ok(_get_client().read("GetUpdate", {"id": id}))


def get_user_group(user_group: str):
    """GetUserGroup.

    user_group: Name or Id
    """
    return _ok(_get_client().read("GetUserGroup", {"user_group": user_group}))


def get_username(user_id: str):
    """GetUsername.

    user_id: The id of the user.
    """
    return _ok(_get_client().read("GetUsername", {"user_id": user_id}))


def get_variable(name: str):
    """GetVariable.

    name: The name of the variable to get.
    """
    return _ok(_get_client().read("GetVariable", {"name": name}))


def get_version():
    """GetVersion. Returns MCP package version and Komodo service version."""
    from importlib.metadata import version
    return {"mcp": version("komodo-mcp"), "service": _get_client().read("GetVersion")}


def inspect_deployment_container(deployment: str):
    """InspectDeploymentContainer.

    deployment: Id or name
    """
    return _ok(_get_client().read("InspectDeploymentContainer", {"deployment": deployment}))


def inspect_docker_container(server: str, container: str):
    """InspectDockerContainer.

    server: Id or name
    container: The container name
    """
    return _ok(_get_client().read("InspectDockerContainer", {"server": server, "container": container}))


def inspect_docker_image(server: str, image: str):
    """InspectDockerImage.

    server: Id or name
    image: The image name
    """
    return _ok(_get_client().read("InspectDockerImage", {"server": server, "image": image}))


def inspect_docker_network(server: str, network: str):
    """InspectDockerNetwork.

    server: Id or name
    network: The network name
    """
    return _ok(_get_client().read("InspectDockerNetwork", {"server": server, "network": network}))


def inspect_docker_volume(server: str, volume: str):
    """InspectDockerVolume.

    server: Id or name
    volume: The volume name
    """
    return _ok(_get_client().read("InspectDockerVolume", {"server": server, "volume": volume}))


def inspect_stack_container(stack: str, service: str):
    """InspectStackContainer.

    stack: Id or name
    service: The service name to inspect
    """
    return _ok(_get_client().read("InspectStackContainer", {"stack": stack, "service": service}))


def list_actions(query: dict | None = None):
    """ListActions.

    query: optional structured query to filter actions.
    """
    params: dict = {}
    if query is not None:
        params["query"] = query
    return _ok(_get_client().read("ListActions", params or None))


def list_alerters(query: dict | None = None):
    """ListAlerters.

    query: Structured query to filter alerters.
    """
    params: dict = {}
    if query is not None:
        params["query"] = query
    return _ok(_get_client().read("ListAlerters", params or None))


def list_alerts(query: dict | None = None, page: dict | None = None):
    """ListAlerts.

    query: Pass a custom mongo query to filter the alerts.
    page: Retrieve older results by incrementing the page.
    """
    params: dict = {}
    if query is not None:
        params["query"] = query
    if page is not None:
        params["page"] = page
    return _ok(_get_client().read("ListAlerts", params or None))


def list_all_docker_containers(servers: list[str] | None = None):
    """ListAllDockerContainers.

    servers: Filter by server id or name.
    """
    params: dict = {}
    if servers is not None:
        params["servers"] = servers
    return _ok(_get_client().read("ListAllDockerContainers", params or None))


def list_api_keys():
    """ListApiKeys."""
    return _ok(_get_client().read("ListApiKeys"))


def list_api_keys_for_service_user(user: str):
    """ListApiKeysForServiceUser.

    user: Id or username
    """
    return _ok(_get_client().read("ListApiKeysForServiceUser", {"user": user}))


def list_builders(query: dict | None = None):
    """ListBuilders."""
    params: dict = {}
    if query is not None:
        params["query"] = query
    return _ok(_get_client().read("ListBuilders", params or None))


def list_builds(query: dict | None = None):
    """ListBuilds.

    query: optional structured query to filter builds.
    """
    params: dict = {}
    if query is not None:
        params["query"] = query
    return _ok(_get_client().read("ListBuilds", params or None))


def list_build_versions(build: str, major: int | None = None, minor: int | None = None, patch: int | None = None, limit: int | None = None):
    """ListBuildVersions.

    build: Id or name
    major: Filter to only include versions matching this major version.
    minor: Filter to only include versions matching this minor version.
    patch: Filter to only include versions matching this patch version.
    limit: Limit the number of included results. Default is no limit.
    """
    params: dict = {"build": build}
    if major is not None:
        params["major"] = major
    if minor is not None:
        params["minor"] = minor
    if patch is not None:
        params["patch"] = patch
    if limit is not None:
        params["limit"] = limit
    return _ok(_get_client().read("ListBuildVersions", params))


def list_common_build_extra_args(query: dict | None = None):
    """ListCommonBuildExtraArgs.

    query: optional structured query to filter builds.
    """
    params: dict = {}
    if query is not None:
        params["query"] = query
    return _ok(_get_client().read("ListCommonBuildExtraArgs", params or None))


def list_common_deployment_extra_args(query: dict | None = None):
    """ListCommonDeploymentExtraArgs.

    query: optional structured query to filter deployments.
    """
    params: dict = {}
    if query is not None:
        params["query"] = query
    return _ok(_get_client().read("ListCommonDeploymentExtraArgs", params or None))


def list_common_stack_build_extra_args(query: dict | None = None):
    """ListCommonStackBuildExtraArgs.

    query: optional structured query to filter stacks.
    """
    params: dict = {}
    if query is not None:
        params["query"] = query
    return _ok(_get_client().read("ListCommonStackBuildExtraArgs", params or None))


def list_common_stack_extra_args(query: dict | None = None):
    """ListCommonStackExtraArgs.

    query: optional structured query to filter stacks.
    """
    params: dict = {}
    if query is not None:
        params["query"] = query
    return _ok(_get_client().read("ListCommonStackExtraArgs", params or None))


def list_compose_projects(server: str):
    """ListComposeProjects.

    server: Id or name
    """
    return _ok(_get_client().read("ListComposeProjects", {"server": server}))


def list_deployments(query: dict | None = None):
    """ListDeployments.

    query: optional structured query to filter deployments.
    """
    params: dict = {}
    if query is not None:
        params["query"] = query
    return _ok(_get_client().read("ListDeployments", params or None))


def list_docker_containers(server: str):
    """ListDockerContainers.

    server: Id or name
    """
    return _ok(_get_client().read("ListDockerContainers", {"server": server}))


def list_docker_image_history(server: str, image: str):
    """ListDockerImageHistory.

    server: Id or name
    image: The image name
    """
    return _ok(_get_client().read("ListDockerImageHistory", {"server": server, "image": image}))


def list_docker_images(server: str):
    """ListDockerImages.

    server: Id or name
    """
    return _ok(_get_client().read("ListDockerImages", {"server": server}))


def list_docker_networks(server: str):
    """ListDockerNetworks.

    server: Id or name
    """
    return _ok(_get_client().read("ListDockerNetworks", {"server": server}))


def list_docker_registries_from_config(target: dict | None = None):
    """ListDockerRegistriesFromConfig.

    target: Accepts an optional Server or Builder target to expand the core list with
    """
    params: dict = {}
    if target is not None:
        params["target"] = target
    return _ok(_get_client().read("ListDockerRegistriesFromConfig", params or None))


def list_docker_registry_accounts(domain: str | None = None, username: str | None = None):
    """ListDockerRegistryAccounts.

    domain: Optionally filter by accounts with a specific domain.
    username: Optionally filter by accounts with a specific username.
    """
    params: dict = {}
    if domain is not None:
        params["domain"] = domain
    if username is not None:
        params["username"] = username
    return _ok(_get_client().read("ListDockerRegistryAccounts", params or None))


def list_docker_volumes(server: str):
    """ListDockerVolumes.

    server: Id or name
    """
    return _ok(_get_client().read("ListDockerVolumes", {"server": server}))


def list_full_actions(query: dict | None = None):
    """ListFullActions.

    query: optional structured query to filter actions.
    """
    params: dict = {}
    if query is not None:
        params["query"] = query
    return _ok(_get_client().read("ListFullActions", params or None))


def list_full_alerters(query: dict | None = None):
    """ListFullAlerters.

    query: Structured query to filter alerters.
    """
    params: dict = {}
    if query is not None:
        params["query"] = query
    return _ok(_get_client().read("ListFullAlerters", params or None))


def list_full_builders(query: dict | None = None):
    """ListFullBuilders."""
    params: dict = {}
    if query is not None:
        params["query"] = query
    return _ok(_get_client().read("ListFullBuilders", params or None))


def list_full_builds(query: dict | None = None):
    """ListFullBuilds.

    query: optional structured query to filter builds.
    """
    params: dict = {}
    if query is not None:
        params["query"] = query
    return _ok(_get_client().read("ListFullBuilds", params or None))


def list_full_deployments(query: dict | None = None):
    """ListFullDeployments.

    query: optional structured query to filter deployments.
    """
    params: dict = {}
    if query is not None:
        params["query"] = query
    return _ok(_get_client().read("ListFullDeployments", params or None))


def list_full_procedures(query: dict | None = None):
    """ListFullProcedures.

    query: optional structured query to filter procedures.
    """
    params: dict = {}
    if query is not None:
        params["query"] = query
    return _ok(_get_client().read("ListFullProcedures", params or None))


def list_full_repos(query: dict | None = None):
    """ListFullRepos.

    query: optional structured query to filter repos.
    """
    params: dict = {}
    if query is not None:
        params["query"] = query
    return _ok(_get_client().read("ListFullRepos", params or None))


def list_full_resource_syncs(query: dict | None = None):
    """ListFullResourceSyncs.

    query: optional structured query to filter syncs.
    """
    params: dict = {}
    if query is not None:
        params["query"] = query
    return _ok(_get_client().read("ListFullResourceSyncs", params or None))


def list_full_servers(query: dict | None = None):
    """ListFullServers.

    query: optional structured query to filter servers.
    """
    params: dict = {}
    if query is not None:
        params["query"] = query
    return _ok(_get_client().read("ListFullServers", params or None))


def list_full_stacks(query: dict | None = None):
    """ListFullStacks.

    query: optional structured query to filter stacks.
    """
    params: dict = {}
    if query is not None:
        params["query"] = query
    return _ok(_get_client().read("ListFullStacks", params or None))


def list_git_provider_accounts(domain: str | None = None, username: str | None = None):
    """ListGitProviderAccounts.

    domain: Optionally filter by accounts with a specific domain.
    username: Optionally filter by accounts with a specific username.
    """
    params: dict = {}
    if domain is not None:
        params["domain"] = domain
    if username is not None:
        params["username"] = username
    return _ok(_get_client().read("ListGitProviderAccounts", params or None))


def list_git_providers_from_config(target: dict | None = None):
    """ListGitProvidersFromConfig.

    target: Accepts an optional Server or Builder target to expand the core list with
    """
    params: dict = {}
    if target is not None:
        params["target"] = target
    return _ok(_get_client().read("ListGitProvidersFromConfig", params or None))


def list_permissions():
    """ListPermissions."""
    return _ok(_get_client().read("ListPermissions"))


def list_procedures(query: dict | None = None):
    """ListProcedures.

    query: optional structured query to filter procedures.
    """
    params: dict = {}
    if query is not None:
        params["query"] = query
    return _ok(_get_client().read("ListProcedures", params or None))


def list_repos(query: dict | None = None):
    """ListRepos.

    query: optional structured query to filter repos.
    """
    params: dict = {}
    if query is not None:
        params["query"] = query
    return _ok(_get_client().read("ListRepos", params or None))


def list_resource_syncs(query: dict | None = None):
    """ListResourceSyncs.

    query: optional structured query to filter syncs.
    """
    params: dict = {}
    if query is not None:
        params["query"] = query
    return _ok(_get_client().read("ListResourceSyncs", params or None))


def list_schedules(tags: list[str] | None = None, tag_behavior: str | None = None):
    """ListSchedules.

    tags: Pass Vec of tag ids or tag names
    tag_behavior: 'All' or 'Any'
    """
    params: dict = {}
    if tags is not None:
        params["tags"] = tags
    if tag_behavior is not None:
        params["tag_behavior"] = tag_behavior
    return _ok(_get_client().read("ListSchedules", params or None))


def list_secrets(target: dict | None = None):
    """ListSecrets.

    target: Accepts an optional Server or Builder target to expand the core list with
    """
    params: dict = {}
    if target is not None:
        params["target"] = target
    return _ok(_get_client().read("ListSecrets", params or None))


def list_servers(query: dict | None = None):
    """ListServers.

    query: optional structured query to filter servers.
    """
    params: dict = {}
    if query is not None:
        params["query"] = query
    return _ok(_get_client().read("ListServers", params or None))


def list_stacks(query: dict | None = None):
    """ListStacks.

    query: optional structured query to filter stacks.
    """
    params: dict = {}
    if query is not None:
        params["query"] = query
    return _ok(_get_client().read("ListStacks", params or None))


def list_stack_services(stack: str):
    """ListStackServices.

    stack: Id or name
    """
    return _ok(_get_client().read("ListStackServices", {"stack": stack}))


def list_system_processes(server: str):
    """ListSystemProcesses.

    server: Id or name
    """
    return _ok(_get_client().read("ListSystemProcesses", {"server": server}))


def list_tags(query: dict | None = None):
    """ListTags."""
    params: dict = {}
    if query is not None:
        params["query"] = query
    return _ok(_get_client().read("ListTags", params or None))


def list_terminals(server: str, fresh: bool | None = None):
    """ListTerminals.

    server: Id or name
    fresh: Force a fresh call to Periphery for the list.
    """
    params: dict = {"server": server}
    if fresh is not None:
        params["fresh"] = fresh
    return _ok(_get_client().read("ListTerminals", params))


def list_updates(query: dict | None = None, page: int | None = None):
    """ListUpdates.

    query: An optional mongo query to filter the updates.
    page: Page of updates. Default is 0, which is the most recent data.
    """
    params: dict = {}
    if query is not None:
        params["query"] = query
    if page is not None:
        params["page"] = page
    return _ok(_get_client().read("ListUpdates", params or None))


def list_user_groups():
    """ListUserGroups."""
    return _ok(_get_client().read("ListUserGroups"))


def list_users():
    """ListUsers."""
    return _ok(_get_client().read("ListUsers"))


def list_user_target_permissions(user_target: dict):
    """ListUserTargetPermissions.

    user_target: Specify either a user or a user group.
    """
    return _ok(_get_client().read("ListUserTargetPermissions", {"user_target": user_target}))


def list_variables():
    """ListVariables."""
    return _ok(_get_client().read("ListVariables"))


def search_container_log(server: str, container: str, terms: list[str], combinator: str | None = None, invert: bool | None = None, timestamps: bool | None = None):
    """SearchContainerLog.

    server: Id or name
    container: The container name
    terms: The terms to search for.
    combinator: When searching for multiple terms, can use `AND` or `OR` combinator.
    invert: Invert the results, ie return all lines that DON'T match the terms / combinator.
    timestamps: Enable `--timestamps`
    """
    params: dict = {"server": server, "container": container, "terms": terms}
    if combinator is not None:
        params["combinator"] = combinator
    if invert is not None:
        params["invert"] = invert
    if timestamps is not None:
        params["timestamps"] = timestamps
    return _ok(_get_client().read("SearchContainerLog", params))


def search_deployment_log(deployment: str, terms: list[str], combinator: str | None = None, invert: bool | None = None, timestamps: bool | None = None):
    """SearchDeploymentLog.

    deployment: Id or name
    terms: The terms to search for.
    combinator: When searching for multiple terms, can use `AND` or `OR` combinator.
    invert: Invert the results, ie return all lines that DON'T match the terms / combinator.
    timestamps: Enable `--timestamps`
    """
    params: dict = {"deployment": deployment, "terms": terms}
    if combinator is not None:
        params["combinator"] = combinator
    if invert is not None:
        params["invert"] = invert
    if timestamps is not None:
        params["timestamps"] = timestamps
    return _ok(_get_client().read("SearchDeploymentLog", params))


def search_stack_log(stack: str, services: list[str], terms: list[str], combinator: str | None = None, invert: bool | None = None, timestamps: bool | None = None):
    """SearchStackLog.

    stack: Id or name
    services: Filter the logs to only ones from specific services.
    terms: The terms to search for.
    combinator: When searching for multiple terms, can use `AND` or `OR` combinator.
    invert: Invert the results, ie return all lines that DON'T match the terms / combinator.
    timestamps: Enable `--timestamps`
    """
    params: dict = {"stack": stack, "services": services, "terms": terms}
    if combinator is not None:
        params["combinator"] = combinator
    if invert is not None:
        params["invert"] = invert
    if timestamps is not None:
        params["timestamps"] = timestamps
    return _ok(_get_client().read("SearchStackLog", params))


# ── write ───────────────────────────────────────────────────────────────

def add_user_to_user_group(user_group: str, user: str):
    """AddUserToUserGroup.

    user_group: The name or id of UserGroup that user should be added to.
    user: The id or username of the user to add
    """
    return _ok(_get_client().write("AddUserToUserGroup", {"user_group": user_group, "user": user}))


def commit_sync(sync: str):
    """CommitSync.

    sync: Id or name
    """
    return _ok(_get_client().write("CommitSync", {"sync": sync}))


def copy_action(name: str, id: str):
    """CopyAction.

    name: The name of the new action.
    id: The id of the action to copy.
    """
    return _ok(_get_client().write("CopyAction", {"name": name, "id": id}))


def copy_alerter(name: str, id: str):
    """CopyAlerter.

    name: The name of the new alerter.
    id: The id of the alerter to copy.
    """
    return _ok(_get_client().write("CopyAlerter", {"name": name, "id": id}))


def copy_build(name: str, id: str):
    """CopyBuild.

    name: The name of the new build.
    id: The id of the build to copy.
    """
    return _ok(_get_client().write("CopyBuild", {"name": name, "id": id}))


def copy_builder(name: str, id: str):
    """CopyBuilder.

    name: The name of the new builder.
    id: The id of the builder to copy.
    """
    return _ok(_get_client().write("CopyBuilder", {"name": name, "id": id}))


def copy_deployment(name: str, id: str):
    """CopyDeployment.

    name: The name of the new deployment.
    id: The id of the deployment to copy.
    """
    return _ok(_get_client().write("CopyDeployment", {"name": name, "id": id}))


def copy_procedure(name: str, id: str):
    """CopyProcedure.

    name: The name of the new procedure.
    id: The id of the procedure to copy.
    """
    return _ok(_get_client().write("CopyProcedure", {"name": name, "id": id}))


def copy_repo(name: str, id: str):
    """CopyRepo.

    name: The name of the new repo.
    id: The id of the repo to copy.
    """
    return _ok(_get_client().write("CopyRepo", {"name": name, "id": id}))


def copy_resource_sync(name: str, id: str):
    """CopyResourceSync.

    name: The name of the new sync.
    id: The id of the sync to copy.
    """
    return _ok(_get_client().write("CopyResourceSync", {"name": name, "id": id}))


def copy_server(name: str, id: str):
    """CopyServer.

    name: The name of the new server.
    id: The id of the server to copy.
    """
    return _ok(_get_client().write("CopyServer", {"name": name, "id": id}))


def copy_stack(name: str, id: str):
    """CopyStack.

    name: The name of the new stack.
    id: The id of the stack to copy.
    """
    return _ok(_get_client().write("CopyStack", {"name": name, "id": id}))


def create_action(name: str, config: dict | None = None):
    """CreateAction.

    name: The name given to newly created action.
    config: Optional partial config to initialize the action with.
    """
    params: dict = {"name": name}
    if config is not None:
        params["config"] = config
    return _ok(_get_client().write("CreateAction", params))


def create_alerter(name: str, config: dict | None = None):
    """CreateAlerter.

    name: The name given to newly created alerter.
    config: Optional partial config to initialize the alerter with.
    """
    params: dict = {"name": name}
    if config is not None:
        params["config"] = config
    return _ok(_get_client().write("CreateAlerter", params))


def create_api_key_for_service_user(user_id: str, name: str, expires: int | None = None):
    """CreateApiKeyForServiceUser.

    user_id: Must be service user
    name: The name for the api key
    expires: A unix timestamp in millseconds specifying api key expire time.
    """
    params: dict = {"user_id": user_id, "name": name}
    if expires is not None:
        params["expires"] = expires
    return _ok(_get_client().write("CreateApiKeyForServiceUser", params))


def create_build(name: str, config: dict | None = None):
    """CreateBuild.

    name: The name given to newly created build.
    config: Optional partial config to initialize the build with.
    """
    params: dict = {"name": name}
    if config is not None:
        params["config"] = config
    return _ok(_get_client().write("CreateBuild", params))


def create_builder(name: str, config: dict | None = None):
    """CreateBuilder.

    name: The name given to newly created builder.
    config: Optional partial config to initialize the builder with.
    """
    params: dict = {"name": name}
    if config is not None:
        params["config"] = config
    return _ok(_get_client().write("CreateBuilder", params))


def create_build_webhook(build: str):
    """CreateBuildWebhook.

    build: Id or name
    """
    return _ok(_get_client().write("CreateBuildWebhook", {"build": build}))


def create_deployment(name: str, config: dict | None = None):
    """CreateDeployment.

    name: The name given to newly created deployment.
    config: Optional partial config to initialize the deployment with.
    """
    params: dict = {"name": name}
    if config is not None:
        params["config"] = config
    return _ok(_get_client().write("CreateDeployment", params))


def create_deployment_from_container(name: str, server: str):
    """CreateDeploymentFromContainer.

    name: The name or id of the existing container.
    server: The server id or name on which container exists.
    """
    return _ok(_get_client().write("CreateDeploymentFromContainer", {"name": name, "server": server}))


def create_docker_registry_account(account: dict):
    """CreateDockerRegistryAccount."""
    return _ok(_get_client().write("CreateDockerRegistryAccount", {"account": account}))


def create_git_provider_account(account: dict):
    """CreateGitProviderAccount.

    account: The initial account config. Anything in the _id field will be ignored,
    """
    return _ok(_get_client().write("CreateGitProviderAccount", {"account": account}))


def create_local_user(username: str, password: str):
    """CreateLocalUser.

    username: The username for the local user.
    password: A password for the local user.
    """
    return _ok(_get_client().write("CreateLocalUser", {"username": username, "password": password}))


def create_network(server: str, name: str):
    """CreateNetwork.

    server: Server Id or name
    name: The name of the network to create.
    """
    return _ok(_get_client().write("CreateNetwork", {"server": server, "name": name}))


def create_procedure(name: str, config: dict | None = None):
    """CreateProcedure.

    name: The name given to newly created build.
    config: Optional partial config to initialize the procedure with.
    """
    params: dict = {"name": name}
    if config is not None:
        params["config"] = config
    return _ok(_get_client().write("CreateProcedure", params))


def create_repo(name: str, config: dict | None = None):
    """CreateRepo.

    name: The name given to newly created repo.
    config: Optional partial config to initialize the repo with.
    """
    params: dict = {"name": name}
    if config is not None:
        params["config"] = config
    return _ok(_get_client().write("CreateRepo", params))


def create_repo_webhook(repo: str, action: dict):
    """CreateRepoWebhook.

    repo: Id or name
    action: "Clone" or "Pull" or "Build"
    """
    return _ok(_get_client().write("CreateRepoWebhook", {"repo": repo, "action": action}))


def create_resource_sync(name: str, config: dict | None = None):
    """CreateResourceSync.

    name: The name given to newly created sync.
    config: Optional partial config to initialize the sync with.
    """
    params: dict = {"name": name}
    if config is not None:
        params["config"] = config
    return _ok(_get_client().write("CreateResourceSync", params))


def create_server(name: str, config: dict | None = None):
    """CreateServer.

    name: The name given to newly created server.
    config: Optional partial config to initialize the server with.
    """
    params: dict = {"name": name}
    if config is not None:
        params["config"] = config
    return _ok(_get_client().write("CreateServer", params))


def create_service_user(username: str, description: str):
    """CreateServiceUser.

    username: The username for the service user.
    description: A description for the service user.
    """
    return _ok(_get_client().write("CreateServiceUser", {"username": username, "description": description}))


def create_stack(name: str, config: dict | None = None):
    """CreateStack.

    name: The name given to newly created stack.
    config: Optional partial config to initialize the stack with.
    """
    params: dict = {"name": name}
    if config is not None:
        params["config"] = config
    return _ok(_get_client().write("CreateStack", params))


def create_stack_webhook(stack: str, action: dict):
    """CreateStackWebhook.

    stack: Id or name
    action: "Refresh" or "Deploy"
    """
    return _ok(_get_client().write("CreateStackWebhook", {"stack": stack, "action": action}))


def create_sync_webhook(sync: str, action: dict):
    """CreateSyncWebhook.

    sync: Id or name
    action: "Refresh" or "Sync"
    """
    return _ok(_get_client().write("CreateSyncWebhook", {"sync": sync, "action": action}))


def create_tag(name: str, color: dict | None = None):
    """CreateTag.

    name: The name of the tag.
    color: Tag color. Default: Slate.
    """
    params: dict = {"name": name}
    if color is not None:
        params["color"] = color
    return _ok(_get_client().write("CreateTag", params))


def create_terminal(server: str, name: str, command: str, recreate: str | None = None):
    """CreateTerminal.

    server: Server Id or name
    name: The name of the terminal on the server to create.
    command: The shell command (eg `bash`) to init the shell.
    recreate: Default: `Never`
    """
    params: dict = {"server": server, "name": name, "command": command}
    if recreate is not None:
        params["recreate"] = recreate
    return _ok(_get_client().write("CreateTerminal", params))


def create_user_group(name: str):
    """CreateUserGroup.

    name: The name to assign to the new UserGroup
    """
    return _ok(_get_client().write("CreateUserGroup", {"name": name}))


def create_variable(name: str, value: str | None = None, description: str | None = None, is_secret: bool | None = None):
    """CreateVariable.

    name: The name of the variable to create.
    value: The initial value of the variable. defualt: "".
    description: The initial value of the description. default: "".
    is_secret: Whether to make this a secret variable.
    """
    params: dict = {"name": name}
    if value is not None:
        params["value"] = value
    if description is not None:
        params["description"] = description
    if is_secret is not None:
        params["is_secret"] = is_secret
    return _ok(_get_client().write("CreateVariable", params))


def delete_action(id: str):
    """DeleteAction.

    id: The id or name of the action to delete.
    """
    return _ok(_get_client().write("DeleteAction", {"id": id}))


def delete_alerter(id: str):
    """DeleteAlerter.

    id: The id or name of the alerter to delete.
    """
    return _ok(_get_client().write("DeleteAlerter", {"id": id}))


def delete_all_terminals(server: str):
    """DeleteAllTerminals.

    server: Server Id or name
    """
    return _ok(_get_client().write("DeleteAllTerminals", {"server": server}))


def delete_api_key_for_service_user(key: str):
    """DeleteApiKeyForServiceUser."""
    return _ok(_get_client().write("DeleteApiKeyForServiceUser", {"key": key}))


def delete_build(id: str):
    """DeleteBuild.

    id: The id or name of the build to delete.
    """
    return _ok(_get_client().write("DeleteBuild", {"id": id}))


def delete_builder(id: str):
    """DeleteBuilder.

    id: The id or name of the builder to delete.
    """
    return _ok(_get_client().write("DeleteBuilder", {"id": id}))


def delete_build_webhook(build: str):
    """DeleteBuildWebhook.

    build: Id or name
    """
    return _ok(_get_client().write("DeleteBuildWebhook", {"build": build}))


def delete_deployment(id: str):
    """DeleteDeployment.

    id: The id or name of the deployment to delete.
    """
    return _ok(_get_client().write("DeleteDeployment", {"id": id}))


def delete_docker_registry_account(id: str):
    """DeleteDockerRegistryAccount.

    id: The id of the docker registry account to delete
    """
    return _ok(_get_client().write("DeleteDockerRegistryAccount", {"id": id}))


def delete_git_provider_account(id: str):
    """DeleteGitProviderAccount.

    id: The id of the git provider to delete
    """
    return _ok(_get_client().write("DeleteGitProviderAccount", {"id": id}))


def delete_procedure(id: str):
    """DeleteProcedure.

    id: The id or name of the procedure to delete.
    """
    return _ok(_get_client().write("DeleteProcedure", {"id": id}))


def delete_repo(id: str):
    """DeleteRepo.

    id: The id or name of the repo to delete.
    """
    return _ok(_get_client().write("DeleteRepo", {"id": id}))


def delete_repo_webhook(repo: str, action: dict):
    """DeleteRepoWebhook.

    repo: Id or name
    action: "Clone" or "Pull" or "Build"
    """
    return _ok(_get_client().write("DeleteRepoWebhook", {"repo": repo, "action": action}))


def delete_resource_sync(id: str):
    """DeleteResourceSync.

    id: The id or name of the sync to delete.
    """
    return _ok(_get_client().write("DeleteResourceSync", {"id": id}))


def delete_server(id: str):
    """DeleteServer.

    id: The id or name of the server to delete.
    """
    return _ok(_get_client().write("DeleteServer", {"id": id}))


def delete_stack(id: str):
    """DeleteStack.

    id: The id or name of the stack to delete.
    """
    return _ok(_get_client().write("DeleteStack", {"id": id}))


def delete_stack_webhook(stack: str, action: dict):
    """DeleteStackWebhook.

    stack: Id or name
    action: "Refresh" or "Deploy"
    """
    return _ok(_get_client().write("DeleteStackWebhook", {"stack": stack, "action": action}))


def delete_sync_webhook(sync: str, action: dict):
    """DeleteSyncWebhook.

    sync: Id or name
    action: "Refresh" or "Sync"
    """
    return _ok(_get_client().write("DeleteSyncWebhook", {"sync": sync, "action": action}))


def delete_tag(id: str):
    """DeleteTag.

    id: The id of the tag to delete.
    """
    return _ok(_get_client().write("DeleteTag", {"id": id}))


def delete_terminal(server: str, terminal: str):
    """DeleteTerminal.

    server: Server Id or name
    terminal: The name of the terminal on the server to delete.
    """
    return _ok(_get_client().write("DeleteTerminal", {"server": server, "terminal": terminal}))


def delete_user(user: str):
    """DeleteUser.

    user: User id or username
    """
    return _ok(_get_client().write("DeleteUser", {"user": user}))


def delete_user_group(id: str):
    """DeleteUserGroup.

    id: The id of the UserGroup
    """
    return _ok(_get_client().write("DeleteUserGroup", {"id": id}))


def delete_variable(name: str):
    """DeleteVariable."""
    return _ok(_get_client().write("DeleteVariable", {"name": name}))


def refresh_build_cache(build: str):
    """RefreshBuildCache.

    build: Id or name
    """
    return _ok(_get_client().write("RefreshBuildCache", {"build": build}))


def refresh_repo_cache(repo: str):
    """RefreshRepoCache.

    repo: Id or name
    """
    return _ok(_get_client().write("RefreshRepoCache", {"repo": repo}))


def refresh_resource_sync_pending(sync: str):
    """RefreshResourceSyncPending.

    sync: Id or name
    """
    return _ok(_get_client().write("RefreshResourceSyncPending", {"sync": sync}))


def refresh_stack_cache(stack: str):
    """RefreshStackCache.

    stack: Id or name
    """
    return _ok(_get_client().write("RefreshStackCache", {"stack": stack}))


def remove_user_from_user_group(user_group: str, user: str):
    """RemoveUserFromUserGroup.

    user_group: The name or id of UserGroup that user should be removed from.
    user: The id or username of the user to remove
    """
    return _ok(_get_client().write("RemoveUserFromUserGroup", {"user_group": user_group, "user": user}))


def rename_action(id: str, name: str):
    """RenameAction.

    id: The id or name of the Action to rename.
    name: The new name.
    """
    return _ok(_get_client().write("RenameAction", {"id": id, "name": name}))


def rename_alerter(id: str, name: str):
    """RenameAlerter.

    id: The id or name of the Alerter to rename.
    name: The new name.
    """
    return _ok(_get_client().write("RenameAlerter", {"id": id, "name": name}))


def rename_build(id: str, name: str):
    """RenameBuild.

    id: The id or name of the Build to rename.
    name: The new name.
    """
    return _ok(_get_client().write("RenameBuild", {"id": id, "name": name}))


def rename_builder(id: str, name: str):
    """RenameBuilder.

    id: The id or name of the Builder to rename.
    name: The new name.
    """
    return _ok(_get_client().write("RenameBuilder", {"id": id, "name": name}))


def rename_deployment(id: str, name: str):
    """RenameDeployment.

    id: The id of the deployment to rename.
    name: The new name.
    """
    return _ok(_get_client().write("RenameDeployment", {"id": id, "name": name}))


def rename_procedure(id: str, name: str):
    """RenameProcedure.

    id: The id or name of the Procedure to rename.
    name: The new name.
    """
    return _ok(_get_client().write("RenameProcedure", {"id": id, "name": name}))


def rename_repo(id: str, name: str):
    """RenameRepo.

    id: The id or name of the Repo to rename.
    name: The new name.
    """
    return _ok(_get_client().write("RenameRepo", {"id": id, "name": name}))


def rename_resource_sync(id: str, name: str):
    """RenameResourceSync.

    id: The id or name of the ResourceSync to rename.
    name: The new name.
    """
    return _ok(_get_client().write("RenameResourceSync", {"id": id, "name": name}))


def rename_server(id: str, name: str):
    """RenameServer.

    id: The id or name of the Server to rename.
    name: The new name.
    """
    return _ok(_get_client().write("RenameServer", {"id": id, "name": name}))


def rename_stack(id: str, name: str):
    """RenameStack.

    id: The id of the stack to rename.
    name: The new name.
    """
    return _ok(_get_client().write("RenameStack", {"id": id, "name": name}))


def rename_tag(id: str, name: str):
    """RenameTag.

    id: The id of the tag to rename.
    name: The new name of the tag.
    """
    return _ok(_get_client().write("RenameTag", {"id": id, "name": name}))


def rename_user_group(id: str, name: str):
    """RenameUserGroup.

    id: The id of the UserGroup
    name: The new name for the UserGroup
    """
    return _ok(_get_client().write("RenameUserGroup", {"id": id, "name": name}))


def set_everyone_user_group(user_group: str, everyone: bool):
    """SetEveryoneUserGroup.

    user_group: Id or name.
    everyone: Whether this user group applies to everyone.
    """
    return _ok(_get_client().write("SetEveryoneUserGroup", {"user_group": user_group, "everyone": everyone}))


def set_users_in_user_group(user_group: str, users: list[str]):
    """SetUsersInUserGroup.

    user_group: Id or name.
    users: The user ids or usernames to hard set as the group's users.
    """
    return _ok(_get_client().write("SetUsersInUserGroup", {"user_group": user_group, "users": users}))


def update_action(id: str, config: dict):
    """UpdateAction.

    id: The id of the action to update.
    config: The partial config update to apply.
    """
    return _ok(_get_client().write("UpdateAction", {"id": id, "config": config}))


def update_alerter(id: str, config: dict):
    """UpdateAlerter.

    id: The id of the alerter to update.
    config: The partial config update to apply.
    """
    return _ok(_get_client().write("UpdateAlerter", {"id": id, "config": config}))


def update_build(id: str, config: dict):
    """UpdateBuild.

    id: The id or name of the build to update.
    config: The partial config update to apply.
    """
    return _ok(_get_client().write("UpdateBuild", {"id": id, "config": config}))


def update_builder(id: str, config: dict):
    """UpdateBuilder.

    id: The id of the builder to update.
    config: The partial config update to apply.
    """
    return _ok(_get_client().write("UpdateBuilder", {"id": id, "config": config}))


def update_deployment(id: str, config: dict):
    """UpdateDeployment.

    id: The deployment id to update.
    config: The partial config update.
    """
    return _ok(_get_client().write("UpdateDeployment", {"id": id, "config": config}))


def update_docker_registry_account(id: str, account: dict):
    """UpdateDockerRegistryAccount.

    id: The id of the docker registry to update
    account: The partial docker registry account.
    """
    return _ok(_get_client().write("UpdateDockerRegistryAccount", {"id": id, "account": account}))


def update_git_provider_account(id: str, account: dict):
    """UpdateGitProviderAccount.

    id: The id of the git provider account to update.
    account: The partial git provider account.
    """
    return _ok(_get_client().write("UpdateGitProviderAccount", {"id": id, "account": account}))


def update_permission_on_resource_type(user_target: dict, resource_type: str, permission: dict):
    """UpdatePermissionOnResourceType.

    user_target: Specify the user or user group.
    resource_type: The resource type: eg. Server, Build, Deployment, etc.
    permission: The base permission level.
    """
    return _ok(_get_client().write("UpdatePermissionOnResourceType", {"user_target": user_target, "resource_type": resource_type, "permission": permission}))


def update_permission_on_target(user_target: dict, resource_target: dict, permission: dict):
    """UpdatePermissionOnTarget.

    user_target: Specify the user or user group.
    resource_target: Specify the target resource.
    permission: Specify the permission level.
    """
    return _ok(_get_client().write("UpdatePermissionOnTarget", {"user_target": user_target, "resource_target": resource_target, "permission": permission}))


def update_procedure(id: str, config: dict):
    """UpdateProcedure.

    id: The id of the procedure to update.
    config: The partial config update.
    """
    return _ok(_get_client().write("UpdateProcedure", {"id": id, "config": config}))


def update_repo(id: str, config: dict):
    """UpdateRepo.

    id: The id of the repo to update.
    config: The partial config update to apply.
    """
    return _ok(_get_client().write("UpdateRepo", {"id": id, "config": config}))


def update_resource_meta(target: dict, description: str | None = None, template: bool | None = None, tags: list[str] | None = None):
    """UpdateResourceMeta.

    target: The target resource to set update meta.
    description: New description to set,
    template: New template value (true or false),
    tags: The exact tags to set,
    """
    params: dict = {"target": target}
    if description is not None:
        params["description"] = description
    if template is not None:
        params["template"] = template
    if tags is not None:
        params["tags"] = tags
    return _ok(_get_client().write("UpdateResourceMeta", params))


def update_resource_sync(id: str, config: dict):
    """UpdateResourceSync.

    id: The id of the sync to update.
    config: The partial config update to apply.
    """
    return _ok(_get_client().write("UpdateResourceSync", {"id": id, "config": config}))


def update_server(id: str, config: dict):
    """UpdateServer.

    id: The id or name of the server to update.
    config: The partial config update to apply.
    """
    return _ok(_get_client().write("UpdateServer", {"id": id, "config": config}))


def update_service_user_description(username: str, description: str):
    """UpdateServiceUserDescription.

    username: The service user's username
    description: A new description for the service user.
    """
    return _ok(_get_client().write("UpdateServiceUserDescription", {"username": username, "description": description}))


def update_stack(id: str, config: dict):
    """UpdateStack.

    id: The id of the Stack to update.
    config: The partial config update to apply.
    """
    return _ok(_get_client().write("UpdateStack", {"id": id, "config": config}))


def update_tag_color(tag: str, color: dict):
    """UpdateTagColor.

    tag: The name or id of the tag to update.
    color: The new color for the tag.
    """
    return _ok(_get_client().write("UpdateTagColor", {"tag": tag, "color": color}))


def update_user_admin(user_id: str, admin: bool):
    """UpdateUserAdmin.

    user_id: The target user.
    admin: Whether user should be admin.
    """
    return _ok(_get_client().write("UpdateUserAdmin", {"user_id": user_id, "admin": admin}))


def update_user_base_permissions(user_id: str, enabled: bool | None = None, create_servers: bool | None = None, create_builds: bool | None = None):
    """UpdateUserBasePermissions.

    user_id: The target user.
    enabled: If specified, will update users enabled state.
    create_servers: If specified, will update user's ability to create servers.
    create_builds: If specified, will update user's ability to create builds.
    """
    params: dict = {"user_id": user_id}
    if enabled is not None:
        params["enabled"] = enabled
    if create_servers is not None:
        params["create_servers"] = create_servers
    if create_builds is not None:
        params["create_builds"] = create_builds
    return _ok(_get_client().write("UpdateUserBasePermissions", params))


def update_user_password(password: str):
    """UpdateUserPassword."""
    return _ok(_get_client().write("UpdateUserPassword", {"password": password}))


def update_user_username(username: str):
    """UpdateUserUsername."""
    return _ok(_get_client().write("UpdateUserUsername", {"username": username}))


def update_variable_description(name: str, description: str):
    """UpdateVariableDescription.

    name: The name of the variable to update.
    description: The description to set.
    """
    return _ok(_get_client().write("UpdateVariableDescription", {"name": name, "description": description}))


def update_variable_is_secret(name: str, is_secret: bool):
    """UpdateVariableIsSecret.

    name: The name of the variable to update.
    is_secret: Whether variable is secret.
    """
    return _ok(_get_client().write("UpdateVariableIsSecret", {"name": name, "is_secret": is_secret}))


def update_variable_value(name: str, value: str):
    """UpdateVariableValue.

    name: The name of the variable to update.
    value: The value to set.
    """
    return _ok(_get_client().write("UpdateVariableValue", {"name": name, "value": value}))


def write_build_file_contents(build: str, contents: str):
    """WriteBuildFileContents.

    build: The name or id of the target Build.
    contents: The dockerfile contents to write.
    """
    return _ok(_get_client().write("WriteBuildFileContents", {"build": build, "contents": contents}))


def write_stack_file_contents(stack: str, file_path: str, contents: str):
    """WriteStackFileContents.

    stack: The name or id of the target Stack.
    file_path: The file path relative to the stack run directory,
    contents: The contents to write.
    """
    return _ok(_get_client().write("WriteStackFileContents", {"stack": stack, "file_path": file_path, "contents": contents}))


def write_sync_file_contents(sync: str, resource_path: str, file_path: str, contents: str):
    """WriteSyncFileContents.

    sync: The name or id of the target Sync.
    resource_path: If this file was under a resource folder, this will be the folder.
    file_path: The file path relative to the resource path.
    contents: The contents to write.
    """
    return _ok(_get_client().write("WriteSyncFileContents", {"sync": sync, "resource_path": resource_path, "file_path": file_path, "contents": contents}))


# ── execute ─────────────────────────────────────────────────────────────

def backup_core_database():
    """BackupCoreDatabase."""
    return _ok(_get_client().execute("BackupCoreDatabase"))


def batch_build_repo(pattern: str):
    """BatchBuildRepo.

    pattern: Id or name or wildcard pattern or regex.
    """
    return _ok(_get_client().execute("BatchBuildRepo", {"pattern": pattern}))


def batch_clone_repo(pattern: str):
    """BatchCloneRepo.

    pattern: Id or name or wildcard pattern or regex.
    """
    return _ok(_get_client().execute("BatchCloneRepo", {"pattern": pattern}))


def batch_deploy(pattern: str):
    """BatchDeploy.

    pattern: Id or name or wildcard pattern or regex.
    """
    return _ok(_get_client().execute("BatchDeploy", {"pattern": pattern}))


def batch_deploy_stack(pattern: str):
    """BatchDeployStack.

    pattern: Id or name or wildcard pattern or regex.
    """
    return _ok(_get_client().execute("BatchDeployStack", {"pattern": pattern}))


def batch_deploy_stack_if_changed(pattern: str):
    """BatchDeployStackIfChanged.

    pattern: Id or name or wildcard pattern or regex.
    """
    return _ok(_get_client().execute("BatchDeployStackIfChanged", {"pattern": pattern}))


def batch_destroy_deployment(pattern: str):
    """BatchDestroyDeployment.

    pattern: Id or name or wildcard pattern or regex.
    """
    return _ok(_get_client().execute("BatchDestroyDeployment", {"pattern": pattern}))


def batch_destroy_stack(pattern: str):
    """BatchDestroyStack.

    pattern: Id or name or wildcard pattern or regex.
    """
    return _ok(_get_client().execute("BatchDestroyStack", {"pattern": pattern}))


def batch_pull_repo(pattern: str):
    """BatchPullRepo.

    pattern: Id or name or wildcard pattern or regex.
    """
    return _ok(_get_client().execute("BatchPullRepo", {"pattern": pattern}))


def batch_pull_stack(pattern: str):
    """BatchPullStack.

    pattern: Id or name or wildcard pattern or regex.
    """
    return _ok(_get_client().execute("BatchPullStack", {"pattern": pattern}))


def batch_run_action(pattern: str):
    """BatchRunAction.

    pattern: Id or name or wildcard pattern or regex.
    """
    return _ok(_get_client().execute("BatchRunAction", {"pattern": pattern}))


def batch_run_build(pattern: str):
    """BatchRunBuild.

    pattern: Id or name or wildcard pattern or regex.
    """
    return _ok(_get_client().execute("BatchRunBuild", {"pattern": pattern}))


def batch_run_procedure(pattern: str):
    """BatchRunProcedure.

    pattern: Id or name or wildcard pattern or regex.
    """
    return _ok(_get_client().execute("BatchRunProcedure", {"pattern": pattern}))


def build_repo(repo: str):
    """BuildRepo.

    repo: Id or name
    """
    return _ok(_get_client().execute("BuildRepo", {"repo": repo}))


def cancel_build(build: str):
    """CancelBuild.

    build: Can be id or name
    """
    return _ok(_get_client().execute("CancelBuild", {"build": build}))


def cancel_repo_build(repo: str):
    """CancelRepoBuild.

    repo: Can be id or name
    """
    return _ok(_get_client().execute("CancelRepoBuild", {"repo": repo}))


def clear_repo_cache():
    """ClearRepoCache."""
    return _ok(_get_client().execute("ClearRepoCache"))


def clone_repo(repo: str):
    """CloneRepo.

    repo: Id or name
    """
    return _ok(_get_client().execute("CloneRepo", {"repo": repo}))


def delete_image(server: str, name: str):
    """DeleteImage.

    server: Id or name.
    name: The name of the image to delete.
    """
    return _ok(_get_client().execute("DeleteImage", {"server": server, "name": name}))


def delete_network(server: str, name: str):
    """DeleteNetwork.

    server: Id or name.
    name: The name of the network to delete.
    """
    return _ok(_get_client().execute("DeleteNetwork", {"server": server, "name": name}))


def delete_volume(server: str, name: str):
    """DeleteVolume.

    server: Id or name.
    name: The name of the volume to delete.
    """
    return _ok(_get_client().execute("DeleteVolume", {"server": server, "name": name}))


def deploy(deployment: str, stop_signal: str | None = None, stop_time: int | None = None):
    """Deploy.

    deployment: Name or id
    stop_signal: Override the default termination signal specified in the deployment.
    stop_time: Override the default termination max time.
    """
    params: dict = {"deployment": deployment}
    if stop_signal is not None:
        params["stop_signal"] = stop_signal
    if stop_time is not None:
        params["stop_time"] = stop_time
    return _ok(_get_client().execute("Deploy", params))


def deploy_stack(stack: str, services: list[str] | None = None, stop_time: int | None = None):
    """DeployStack.

    stack: Id or name
    services: Filter to only deploy specific services.
    stop_time: Override the default termination max time.
    """
    params: dict = {"stack": stack}
    if services is not None:
        params["services"] = services
    if stop_time is not None:
        params["stop_time"] = stop_time
    return _ok(_get_client().execute("DeployStack", params))


def deploy_stack_if_changed(stack: str, stop_time: int | None = None):
    """DeployStackIfChanged.

    stack: Id or name
    stop_time: Override the default termination max time.
    """
    params: dict = {"stack": stack}
    if stop_time is not None:
        params["stop_time"] = stop_time
    return _ok(_get_client().execute("DeployStackIfChanged", params))


def destroy_container(server: str, container: str, signal: str | None = None, time: int | None = None):
    """DestroyContainer.

    server: Name or id
    container: The container name
    signal: Override the default termination signal.
    time: Override the default termination max time.
    """
    params: dict = {"server": server, "container": container}
    if signal is not None:
        params["signal"] = signal
    if time is not None:
        params["time"] = time
    return _ok(_get_client().execute("DestroyContainer", params))


def destroy_deployment(deployment: str, signal: str | None = None, time: int | None = None):
    """DestroyDeployment.

    deployment: Name or id.
    signal: Override the default termination signal specified in the deployment.
    time: Override the default termination max time.
    """
    params: dict = {"deployment": deployment}
    if signal is not None:
        params["signal"] = signal
    if time is not None:
        params["time"] = time
    return _ok(_get_client().execute("DestroyDeployment", params))


def destroy_stack(stack: str, services: list[str] | None = None, remove_orphans: bool | None = None, stop_time: int | None = None):
    """DestroyStack.

    stack: Id or name
    services: Filter to only destroy specific services.
    remove_orphans: Pass `--remove-orphans`
    stop_time: Override the default termination max time.
    """
    params: dict = {"stack": stack}
    if services is not None:
        params["services"] = services
    if remove_orphans is not None:
        params["remove_orphans"] = remove_orphans
    if stop_time is not None:
        params["stop_time"] = stop_time
    return _ok(_get_client().execute("DestroyStack", params))


def global_auto_update():
    """GlobalAutoUpdate."""
    return _ok(_get_client().execute("GlobalAutoUpdate"))


def pause_all_containers(server: str):
    """PauseAllContainers.

    server: Name or id
    """
    return _ok(_get_client().execute("PauseAllContainers", {"server": server}))


def pause_container(server: str, container: str):
    """PauseContainer.

    server: Name or id
    container: The container name
    """
    return _ok(_get_client().execute("PauseContainer", {"server": server, "container": container}))


def pause_deployment(deployment: str):
    """PauseDeployment.

    deployment: Name or id
    """
    return _ok(_get_client().execute("PauseDeployment", {"deployment": deployment}))


def pause_stack(stack: str, services: list[str] | None = None):
    """PauseStack.

    stack: Id or name
    services: Filter to only pause specific services.
    """
    params: dict = {"stack": stack}
    if services is not None:
        params["services"] = services
    return _ok(_get_client().execute("PauseStack", params))


def prune_buildx(server: str):
    """PruneBuildx.

    server: Id or name
    """
    return _ok(_get_client().execute("PruneBuildx", {"server": server}))


def prune_containers(server: str):
    """PruneContainers.

    server: Id or name
    """
    return _ok(_get_client().execute("PruneContainers", {"server": server}))


def prune_docker_builders(server: str):
    """PruneDockerBuilders.

    server: Id or name
    """
    return _ok(_get_client().execute("PruneDockerBuilders", {"server": server}))


def prune_images(server: str):
    """PruneImages.

    server: Id or name
    """
    return _ok(_get_client().execute("PruneImages", {"server": server}))


def prune_networks(server: str):
    """PruneNetworks.

    server: Id or name
    """
    return _ok(_get_client().execute("PruneNetworks", {"server": server}))


def prune_system(server: str):
    """PruneSystem.

    server: Id or name
    """
    return _ok(_get_client().execute("PruneSystem", {"server": server}))


def prune_volumes(server: str):
    """PruneVolumes.

    server: Id or name
    """
    return _ok(_get_client().execute("PruneVolumes", {"server": server}))


def pull_deployment(deployment: str):
    """PullDeployment.

    deployment: Name or id
    """
    return _ok(_get_client().execute("PullDeployment", {"deployment": deployment}))


def pull_repo(repo: str):
    """PullRepo.

    repo: Id or name
    """
    return _ok(_get_client().execute("PullRepo", {"repo": repo}))


def pull_stack(stack: str, services: list[str] | None = None):
    """PullStack.

    stack: Id or name
    services: Filter to only pull specific services.
    """
    params: dict = {"stack": stack}
    if services is not None:
        params["services"] = services
    return _ok(_get_client().execute("PullStack", params))


def restart_all_containers(server: str):
    """RestartAllContainers.

    server: Name or id
    """
    return _ok(_get_client().execute("RestartAllContainers", {"server": server}))


def restart_container(server: str, container: str):
    """RestartContainer.

    server: Name or id
    container: The container name
    """
    return _ok(_get_client().execute("RestartContainer", {"server": server, "container": container}))


def restart_deployment(deployment: str):
    """RestartDeployment.

    deployment: Name or id
    """
    return _ok(_get_client().execute("RestartDeployment", {"deployment": deployment}))


def restart_stack(stack: str, services: list[str] | None = None):
    """RestartStack.

    stack: Id or name
    services: Filter to only restart specific services.
    """
    params: dict = {"stack": stack}
    if services is not None:
        params["services"] = services
    return _ok(_get_client().execute("RestartStack", params))


def run_action(action: str, args: dict | None = None):
    """RunAction.

    action: Id or name
    args: Custom arguments which are merged on top of the default arguments.
    """
    params: dict = {"action": action}
    if args is not None:
        params["args"] = args
    return _ok(_get_client().execute("RunAction", params))


def run_build(build: str):
    """RunBuild.

    build: Can be build id or name
    """
    return _ok(_get_client().execute("RunBuild", {"build": build}))


def run_procedure(procedure: str):
    """RunProcedure.

    procedure: Id or name
    """
    return _ok(_get_client().execute("RunProcedure", {"procedure": procedure}))


def run_stack_service(stack: str, service: str, command: list[str] | None = None, no_tty: bool | None = None, no_deps: bool | None = None, detach: bool | None = None, service_ports: bool | None = None, env: dict | None = None, workdir: str | None = None, user: str | None = None, entrypoint: str | None = None, pull: bool | None = None):
    """RunStackService.

    stack: Id or name
    service: Service to run
    command: Command and args to pass to the service container
    no_tty: Do not allocate TTY
    no_deps: Do not start linked services
    detach: Detach container on run
    service_ports: Map service ports to the host
    env: Extra environment variables for the run
    workdir: Working directory inside the container
    user: User to run as inside the container
    entrypoint: Override the default entrypoint
    pull: Pull the image before running
    """
    params: dict = {"stack": stack, "service": service}
    if command is not None:
        params["command"] = command
    if no_tty is not None:
        params["no_tty"] = no_tty
    if no_deps is not None:
        params["no_deps"] = no_deps
    if detach is not None:
        params["detach"] = detach
    if service_ports is not None:
        params["service_ports"] = service_ports
    if env is not None:
        params["env"] = env
    if workdir is not None:
        params["workdir"] = workdir
    if user is not None:
        params["user"] = user
    if entrypoint is not None:
        params["entrypoint"] = entrypoint
    if pull is not None:
        params["pull"] = pull
    return _ok(_get_client().execute("RunStackService", params))


def run_sync(sync: str, resource_type: str | None = None, resources: list[str] | None = None):
    """RunSync.

    sync: Id or name
    resource_type: Only execute sync on a specific resource type.
    resources: Only execute sync on a specific resources.
    """
    params: dict = {"sync": sync}
    if resource_type is not None:
        params["resource_type"] = resource_type
    if resources is not None:
        params["resources"] = resources
    return _ok(_get_client().execute("RunSync", params))


def send_alert(message: str, level: str | None = None, details: str | None = None, alerters: list[str] | None = None):
    """SendAlert.

    level: The alert level.
    message: The alert message. Required.
    details: The alert details. Optional.
    alerters: Specific alerter names or ids.
    """
    params: dict = {"message": message}
    if level is not None:
        params["level"] = level
    if details is not None:
        params["details"] = details
    if alerters is not None:
        params["alerters"] = alerters
    return _ok(_get_client().execute("SendAlert", params))


def start_all_containers(server: str):
    """StartAllContainers.

    server: Name or id
    """
    return _ok(_get_client().execute("StartAllContainers", {"server": server}))


def start_container(server: str, container: str):
    """StartContainer.

    server: Name or id
    container: The container name
    """
    return _ok(_get_client().execute("StartContainer", {"server": server, "container": container}))


def start_deployment(deployment: str):
    """StartDeployment.

    deployment: Name or id
    """
    return _ok(_get_client().execute("StartDeployment", {"deployment": deployment}))


def start_stack(stack: str, services: list[str] | None = None):
    """StartStack.

    stack: Id or name
    services: Filter to only start specific services.
    """
    params: dict = {"stack": stack}
    if services is not None:
        params["services"] = services
    return _ok(_get_client().execute("StartStack", params))


def stop_all_containers(server: str):
    """StopAllContainers.

    server: Name or id
    """
    return _ok(_get_client().execute("StopAllContainers", {"server": server}))


def stop_container(server: str, container: str, signal: str | None = None, time: int | None = None):
    """StopContainer.

    server: Name or id
    container: The container name
    signal: Override the default termination signal.
    time: Override the default termination max time.
    """
    params: dict = {"server": server, "container": container}
    if signal is not None:
        params["signal"] = signal
    if time is not None:
        params["time"] = time
    return _ok(_get_client().execute("StopContainer", params))


def stop_deployment(deployment: str, signal: str | None = None, time: int | None = None):
    """StopDeployment.

    deployment: Name or id
    signal: Override the default termination signal specified in the deployment.
    time: Override the default termination max time.
    """
    params: dict = {"deployment": deployment}
    if signal is not None:
        params["signal"] = signal
    if time is not None:
        params["time"] = time
    return _ok(_get_client().execute("StopDeployment", params))


def stop_stack(stack: str, stop_time: int | None = None, services: list[str] | None = None):
    """StopStack.

    stack: Id or name
    stop_time: Override the default termination max time.
    services: Filter to only stop specific services.
    """
    params: dict = {"stack": stack}
    if stop_time is not None:
        params["stop_time"] = stop_time
    if services is not None:
        params["services"] = services
    return _ok(_get_client().execute("StopStack", params))


def test_alerter(alerter: str):
    """TestAlerter.

    alerter: Name or id
    """
    return _ok(_get_client().execute("TestAlerter", {"alerter": alerter}))


def unpause_all_containers(server: str):
    """UnpauseAllContainers.

    server: Name or id
    """
    return _ok(_get_client().execute("UnpauseAllContainers", {"server": server}))


def unpause_container(server: str, container: str):
    """UnpauseContainer.

    server: Name or id
    container: The container name
    """
    return _ok(_get_client().execute("UnpauseContainer", {"server": server, "container": container}))


def unpause_deployment(deployment: str):
    """UnpauseDeployment.

    deployment: Name or id
    """
    return _ok(_get_client().execute("UnpauseDeployment", {"deployment": deployment}))


def unpause_stack(stack: str, services: list[str] | None = None):
    """UnpauseStack.

    stack: Id or name
    services: Filter to only unpause specific services.
    """
    params: dict = {"stack": stack}
    if services is not None:
        params["services"] = services
    return _ok(_get_client().execute("UnpauseStack", params))
